### ISSUE TITLE
Dropdown Icon is a Unicode Error

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#105]
<img width="272" alt="screen shot 2018-07-05 at 6 05 35 pm" src="https://user-images.githubusercontent.com/139987/42350348-18e1ef14-807e-11e8-9f94-89a39cf7fbb6.png">

**Comment by Miserlou** [comment]
<img width="492" alt="screen shot 2018-07-05 at 6 07 24 pm" src="https://user-images.githubusercontent.com/139987/42350386-4da584f4-807e-11e8-838c-c1ebbc59701c.png">

**Comment by Miserlou** [comment]
They also still don't work at all, selecting 'Samples' on the download page remains at None.

**Comment by ramenhog** [comment]
Created a separate ticket for functionality: #133
