### ISSUE TITLE
Publication Title Is Shown Even When There Is No Publication

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#107]
<img width="798" alt="screen shot 2018-07-05 at 6 09 16 pm" src="https://user-images.githubusercontent.com/139987/42350434-98122de4-807e-11e8-95a9-7b1ebe83dab6.png">

**Comment by dvenprasad** [comment]
Expected behavior: 

![screen shot 2018-07-06 at 1 43 54 pm](https://user-images.githubusercontent.com/15315514/42392961-abfa5166-8122-11e8-80e8-b93bffad4169.png)
