### ISSUE TITLE
Filters Don't Work

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#108]
https://staging.refine.bio/results?q=neuro&publication=has_publication

<img width="1175" alt="screen shot 2018-07-05 at 6 11 44 pm" src="https://user-images.githubusercontent.com/139987/42350516-e76c47da-807e-11e8-8270-6eb7d139f7dc.png">

Notice has publication is (1), but selecting it still shows 10/12 results.

**Comment by Miserlou** [comment]
This appears to be true of all the filters.

**Comment by dongbohu** [comment]
Two questions for @Miserlou (and maybe @dvenprasad and @jaclyn-taroni):
1. Why the first filter of `Organism` is `Null`? 
2. Why the first filter of `Technology` doesn't have any text?

**Comment by Miserlou** [comment]
It is getting a successful response back from the organisms endpoint, `[{"name":"MUS_MUSCULUS","taxonomy_id":10090},{"name":"HOMO_SAPIENS","taxonomy_id":9606},{"name":"RATTUS_NORVEGICUS","taxonomy_id":10116}]`, but it's also getting a bad value back from the API. Will investigate now, thanks.

**Comment by dongbohu** [comment]
@Miserlou: Here is the reason why `has publication` filter is not working:
When `Has publication` checkbox is selected, the query sent to the web API is: 
```http://.../results?q=...&publication=has_publication```
but the API doesn't understand `publication=has_publication`. The query it understands is: `has_publication=true`, so this query is silently ignored.

Two ways to fix this problem:
1. On the backend, force the API to translate `publication=has_publication` to `has_publication=true`, or:
2. On the front end, change the query from `publication=has_publication` to `has_publication=true`.

I am not an expert on Django-rest-framework, @Miserlou, which one do you prefer?

**Comment by cgreene** [comment]
I think that I prefer 2. Option 1 seems like an odd querystring.

**Comment by dongbohu** [comment]
@cgreene: It does seem more reasonable to fix it on the front end, but currently all filters are rendered by a single component. So the `publication` filter will have to be treated as a special case, which will make the code a little messy. That's why I am a little hesitant.

**Comment by Miserlou** [comment]
Two is the correct option here.

**Comment by dongbohu** [comment]
All right, let me fix it on front end then. Thanks to both of you!

**Comment by dongbohu** [comment]
@Miserlou To make `organism` filter work, I think we should add `organism` in this line:
https://github.com/AlexsLemonade/refinebio/blob/fb1c30a7ff4c4198ed39a172ef7b4187336a7a7a/api/data_refinery_api/views.py#L118
Do you agree?

**Comment by Miserlou** [comment]
It may need to be `organisms__name` or something similar, but yes, that is
where the filtering logic will happen.

**Comment by dongbohu** [comment]
Right. I noticed that your https://github.com/AlexsLemonade/refinebio/pull/396 is addressing the organism issue. Can you add it in that PR? It seems too simple to open another PR.

**Comment by dongbohu** [comment]
`The publication` filter is working here:
http://165.123.67.202:3000/results?q=neuro
Need to fix the error of the number of results per page too.

**Comment by dongbohu** [comment]
Fixed by PR #166.
