### ISSUE TITLE
Search Box Is Misaligned

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#109]
<img width="1224" alt="screen shot 2018-07-05 at 6 13 15 pm" src="https://user-images.githubusercontent.com/139987/42350721-b1408468-807f-11e8-9d18-b7db68c3fe37.png">

Spacings on the search box and all the related buttons seem off. Guides provided for illustration.

**Comment by ramenhog** [comment]
This was discussed in person with @dvenprasad and it was decided that the searchbox should be centered to the page, not horizontally aligned to results.

**Comment by Willv19** [comment]
Can this be closed?

**Comment by Miserlou** [comment]
I still think it looks really shabby.

**Comment by Willv19** [comment]
I had another conversation with @dvenprasad and it was decided that it should stay the way it is currently.
