### ISSUE TITLE
Buttons For Tab Selection On Downloads Page Only Work on the Text

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#110]
<img width="400" alt="screen shot 2018-07-05 at 6 22 49 pm" src="https://user-images.githubusercontent.com/139987/42350908-8a99d35e-8080-11e8-88b8-4d3f87dde7f9.png">

Only the text is clickable on these buttons. This is different behavior from all of the other buttons on the site.

**Comment by ramenhog** [comment]
I will fix the only text clickable issue. @dvenprasad, do we have a hover state for the these tab buttons?

**Comment by dvenprasad** [comment]
@ramenhog  yes we do. 

![screen shot 2018-07-09 at 9 57 33 am](https://user-images.githubusercontent.com/15315514/42454840-960b3792-835e-11e8-9a58-6e9a2d8a589a.png)


The hover color is: #F2F2F2
