### ISSUE TITLE
Modals Have No Close Button, Cannot Be Close On Small Viewports

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#115]
There is no way to close modals on small viewports:

<img width="741" alt="screen shot 2018-07-05 at 6 30 42 pm" src="https://user-images.githubusercontent.com/139987/42351168-965f6eaa-8081-11e8-8f21-c8a1da83071d.png">

**Comment by Willv19** [comment]
Which modals cannot be closed on small viewports? I tried a few and the ones I found could be closed.

**Comment by Miserlou** [comment]
This is resolved.
