### ISSUE TITLE
Clear Filters Link Does Nothing

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#118]
<img width="1297" alt="screen shot 2018-07-05 at 6 36 51 pm" src="https://user-images.githubusercontent.com/139987/42351334-6d697bca-8082-11e8-9536-17f8aba669c4.png">

Clicking Clear Filters appears to have no effect. In fact, no filters are even displayed at all.

**Comment by Willv19** [comment]
As of now, the Clear Filters link does clear the filters on the search field. Unless we should still display the filters in use with no matching results, this ticket can be closed.
