### ISSUE TITLE
Experiments In Current Dataset Are Shown as Addable

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#119]
I already have these experiments in my Dataset.

They are shown as addable in a new search:

<img width="987" alt="screen shot 2018-07-05 at 6 38 50 pm" src="https://user-images.githubusercontent.com/139987/42351379-b4e32ece-8082-11e8-9e7e-33e75d1e222a.png">

Clicking on Add again causes the indicator on the top right to disappear, the button to flash and then return. No other feedback is given.

<img width="979" alt="screen shot 2018-07-05 at 6 39 35 pm" src="https://user-images.githubusercontent.com/139987/42351394-ca16df52-8082-11e8-90e4-264bfb620129.png">

**Comment by Miserlou** [comment]
The behavior is still incorrect. If I add 3 samples to my dataset, it says there are 88 samples in my dataset and the button is not shown.

![screen shot 2018-07-16 at 12 13 45 pm](https://user-images.githubusercontent.com/139987/42769971-caf82b84-88f1-11e8-9bd8-53ac52ce1329.png)

**Comment by dongbohu** [comment]
Is this one fixed by #176?
