### ISSUE TITLE
Removing Experiment From Dataset Isn't Working

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#122]
There is a Remove button that does nothing:

<img width="1159" alt="screen shot 2018-07-05 at 6 41 24 pm" src="https://user-images.githubusercontent.com/139987/42351470-163cab64-8083-11e8-8e0b-e9fb53b2ba67.png">

It's also unclear that this button is even there since it's presented as a link rather than a ghost button.

**Comment by Miserlou** [comment]
Ex: <img width="1048" alt="screen shot 2018-07-05 at 6 42 13 pm" src="https://user-images.githubusercontent.com/139987/42351495-370ddafc-8083-11e8-8389-b3f091fe3ce8.png">

**Comment by Miserlou** [comment]
Actually, it's not even presented as a link, just a text string.

**Comment by ramenhog** [comment]
The button styles do need to get fixed to include a border around them. However, it seems like removing experiments from dataset isn't working in staging, but is working locally. 

It seems like it might be an API issue @Miserlou? I get this error on staging.

![screen shot 2018-07-09 at 9 40 07 am](https://user-images.githubusercontent.com/4724065/42453906-2053f252-835c-11e8-9066-0b6a9a277891.png)
