### ISSUE TITLE
Clicking Back To Results Removes Search Term

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#125]
To reproduct:

Type in Notch, Search
Click on First Item
Click Back to Results
Notch has disappeared from Search Bar

<img width="1562" alt="screen shot 2018-07-05 at 6 49 31 pm" src="https://user-images.githubusercontent.com/139987/42351674-3d1bfaea-8084-11e8-8fb1-a46f4e32b43d.png">

**Comment by Willv19** [comment]
I cannot replicate

**Comment by Willv19** [comment]
Oh, I see. It removes it from the search bar but not from the query string.
