### ISSUE TITLE
Remove From Dataset Button On Experiment Detail Page is Non-Functional

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#127]
Clicking the Remove button does nothing.

<img width="1562" alt="screen shot 2018-07-05 at 6 53 56 pm" src="https://user-images.githubusercontent.com/139987/42351798-d68f208a-8084-11e8-8e50-1c85f2364a2c.png">

**Comment by ramenhog** [comment]
Seems to be the same backend issue mentioned here: https://github.com/AlexsLemonade/refinebio-frontend/issues/122#issuecomment-403482849

**Comment by ramenhog** [comment]
Fixed by fixing the PUT error bug.
