### ISSUE TITLE
Factoid Bar formatting on Search Page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#128]
Current Behavior: 
![screen shot 2018-07-06 at 2 21 49 pm](https://user-images.githubusercontent.com/15315514/42394394-fb50e464-8127-11e8-9143-03b26c57775c.png)

- Add the word 'Samples' after number of samples.
- The line height for the platform name looks like it is less than 1.5. Bump it up to 1.5 for better readability.

**Comment by ramenhog** [comment]
On the experiment page, platform is using `id` not `platform`.
