### ISSUE TITLE
Cannot Add Experiment To Dataset Once Page Has Been Added

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#138]
When you 'Add Page to Dataset' on an experiment view, the 'Added' text changes at the top, not at the page button. This makes it so the 'Add (all) to Dataset' is no longer functional.

Before click (of the **lower** button):
![screen shot 2018-07-10 at 10 10 03 am](https://user-images.githubusercontent.com/139987/42515367-9c80eff6-8429-11e8-99cf-077b25f03a80.png)

After click:
![screen shot 2018-07-10 at 10 10 14 am](https://user-images.githubusercontent.com/139987/42515377-a41edfd4-8429-11e8-9fc3-67f1f48d4365.png)

**Comment by dongbohu** [comment]
Is this one fixed completely by #176?
