### ISSUE TITLE
Samples Can Be Added To The Dataset Multiple Times

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#139]
Go to an experiments page with and press Add Page to Dataset. Press it again. Keep pressing. You can press it infinite times, and the total number of samples in the dataset will continue to go up by 10 forever.

Notice, 310 samples from an experiment with 64:

![screen shot 2018-07-10 at 1 42 58 pm](https://user-images.githubusercontent.com/139987/42527670-504df926-8447-11e8-98d4-b23afeb24031.png)

Possibly related to https://github.com/AlexsLemonade/refinebio-frontend/issues/138

**Comment by Willv19** [comment]
@Miserlou can you still replicate this bug after the backend PR was merged?

**Comment by Miserlou** [comment]
No, closing.
