### ISSUE TITLE
Cannot Add All To Dataset Once Single Sample Has Been Added

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#148]
On the experiment detail page, the Add All to Dataset button gets replaced with Added to Dataset once a single sample is added. This means that the entire experiment can no longer be added at once, which is a problem for experiments which have hundreds of samples.

Before:
![screen shot 2018-07-16 at 10 08 57 am](https://user-images.githubusercontent.com/139987/42763221-63c14772-88e0-11e8-95ee-5c7aefec4da5.png)

After:
![screen shot 2018-07-16 at 10 09 00 am](https://user-images.githubusercontent.com/139987/42763227-6a221358-88e0-11e8-85ea-2dee4fddf9e9.png)

**Comment by Miserlou** [comment]
Related, the Add Page to Dataset button remains, but is broken once a single sample has been added.

**Comment by dongbohu** [comment]
Is it fixed by #176?

**Comment by dvenprasad** [comment]
Just want to note the the current fix isn't the expected behavior. It is a quick fix. 
#130 should be addressed before the public release.
