### ISSUE TITLE
Frontend Updates Break Existing Datasets

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#149]
needs https://github.com/AlexsLemonade/refinebio/issues/777

---

Since there is no mechanism for 'new' datasets, updates to the website which make non trivial changes leave the application in a broken, unrecoverable state. The state sessions should be aware of the fronend version and update accordingly.

I had a dataset in my session, but then the frontend upgraded, so now it just says `%5Bobject` a lot.

![screen shot 2018-07-16 at 10 21 41 am](https://user-images.githubusercontent.com/139987/42763802-0edfcf56-88e2-11e8-8269-f67d2ddba6c7.png)

**Comment by Miserlou** [comment]
Related: https://github.com/AlexsLemonade/refinebio-frontend/issues/170

**Comment by jaclyn-taroni** [comment]
From tech team meeting: The backend should include a header on every response, which specifies the version of the API. The frontend should check that version header and refresh the application if it's higher than the application's version.

**Comment by arielsvn** [comment]
I don't really understand why this happened... a few comments to try to clarify.

> The state sessions should be aware of the frontend version and update accordingly.

When the application is refreshed, the previous state session is cleared and a new one is created. So the latest version of the code is the one that creates the new state.

> I had a dataset in my session, but then the frontend upgraded, so now it just says `%5Bobject` a lot.

I have seen similar errors, but usually when the API changed from sending sample accession codes to sending objects with details of the samples. In this case we also have to update the front end code to handle the changes of the API.

So the latest version of the front end, always has to know how to handle the latest version of the api.

> The backend should include a header on every response, which specifies the version of the API. The frontend should check that version header and refresh the application if it's higher than the application's version.

I assumed every time we make changes to the API, we'll also update the front-end and deploy both at the same time. Is this correct?

Adding the version of the API in every response, will help users that are using the app when the API is updated. In this scenario some requests may start to fail anyways until they refresh the app. But I think this is not what the original ticket was referring to.

I'm missing something??

**Comment by jaclyn-taroni** [comment]
@kurtwheeler: if the model for the dataset for frontend and backend are out of sync, that is when this happens. 
@arielsvn: solution is version info in API

**Comment by arielsvn** [comment]
In https://github.com/AlexsLemonade/refinebio-frontend/pull/410/commits/c55dbe3198b6673ecedf5a2c1ad74adba171b888 we introduced a script to fetch data from the api and save it to a file on every deploy.

We could do the same to fetch the latest version of the backend repo from https://api.github.com/repos/AlexsLemonade/refinebio/tags

**Comment by arielsvn** [comment]
We discussed this issue, there are two cases scenarios that we want to address:

- Users always should get the latest version of the front-end, when they load the page.
@Miserlou recommended that we query api.github.com when the application is started, and trigger a refresh of the page if the user doesn't have the latest version.

- When an user has the application open, and the API is updated.
For this we'll add a header to every request with the API version. The frontend will check when there's a version change and force an update. It might be good to have a custom error screen for this case, to let the user know that the app will be updated.

**Comment by arielsvn** [comment]
Reading [this](https://medium.com/@kellyrmilligan/adjusting-cache-settings-for-create-react-apps-service-worker-40fb0d060635), it seems that we can ensure users always get the latest version of the app if we disable caching on S3 for two files: `index.html` and `service-worker.js`.

@kurtwheeler modified the deploy script accordingly, we'll test it on staging first before deploying to refine.bio.


Also see https://github.com/facebook/create-react-app/issues/3082#issuecomment-327626847
