### ISSUE TITLE
No Way to Scroll Horizontally in Wide Samples Detail List

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#152]
For an experiment with detailed samples information, lots of the details are buried in a frame which cannot be scrolled horizontally.

I can scroll right by middle-clicking and scrolling right, but I wouldn't do this if I didn't know that information wasn't there. Also, it's just a horrible interaction.

Ex: https://staging.refine.bio/experiments/2?ref=search

![screen shot 2018-07-16 at 10 32 35 am](https://user-images.githubusercontent.com/139987/42764529-d8d0fd48-88e3-11e8-8a5c-03ab4a4564b7.png)
![screen shot 2018-07-16 at 10 32 39 am](https://user-images.githubusercontent.com/139987/42764534-db88dfec-88e3-11e8-9f69-a42085518c23.png)

**Comment by Willv19** [comment]
There is a horizontal scroll bar, but it is way at the bottom of the list. @dvenprasad is there a more user-friendly horizontal scrolling scheme that you would suggest?

**Comment by dongbohu** [comment]
Maybe add the scroll bar both at the top and at the bottom?
