### ISSUE TITLE
Datasets Aren't Delivered // Make The Thing Actually Work

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#155]
I have never actually seen a smashed and delivered dataset.

This bug is priority number one.

**Comment by Miserlou** [comment]
Looks like it's trying to a) start the download before fetching the token, b) fetch the token from the wrong server, c) never use the token and d) parse some JSON that isn't JSON then fail completely.

**Comment by Miserlou** [comment]
Waiting for a redeploy to test this, but hopefully it's sorted by the two associated PRs.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/issues/233 might be causing this.

**Comment by arielsvn** [comment]
@Miserlou can we close this?? Now only processed datasets can be added for download and it seems the datasets are being delivered correctly.
