### ISSUE TITLE
Only First 20 of 257 Samples Are Ever Shown Once Per-Page Is Switched

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#157]
Visit https://staging.refine.bio/experiments/56?ref=search

Switch to '50' per page. Notice that now only ~20 are shown, and all subsequent pages are empty.

![screen shot 2018-07-16 at 12 39 13 pm](https://user-images.githubusercontent.com/139987/42771449-434f128e-88f5-11e8-9ed7-a5ee3bbc3ba5.png)

**Comment by Willv19** [comment]
@Miserlou it looks like this was resolved with the latest API deploy. It now works for me on localhost and staging. Can you confirm?

**Comment by Willv19** [comment]
Hold on, https://staging.refine.bio/experiments/56?ref=search is still broken but https://staging.refine.bio/experiments/54?ref=search is fixed. Is there something wrong with the dataset from the first one?

**Comment by Miserlou** [comment]
Fixed.
