### ISSUE TITLE
Application Does Not Appropriately Handle Failure // No Error Page

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#158]
Looking at the logs, it seems there is a total frontend application failure when trying to start processing a dataset.

Rather than show an "Uhoh! There was an error!" message, it shows the the dataset is actually being processed. This is bad, as the user will never receive their data.

![screen shot 2018-07-16 at 12 59 18 pm](https://user-images.githubusercontent.com/139987/42772320-103c5d22-88f8-11e8-8f98-4dad4d9b58d6.png)

Pinging @dvenprasad for UI input here.

**Comment by dvenprasad** [comment]
It should re-direct to the error state. If it has error handling setup, then display the message on the error page below "Uh-oh something went wrong", otherwise use the mockup as is. 

[Mockup](https://user-images.githubusercontent.com/15315514/41125789-78deee38-6a73-11e8-840b-5b1e45b4270d.png)

**Comment by Miserlou** [comment]
I think this is resolved.
