### ISSUE TITLE
Searching by accession number returns no results

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#160]
I searched for [https://staging.refine.bio/experiments/1](https://staging.refine.bio/experiments/1) with it's accession `E-GEOD-10912`. It returns no matching results

![screen shot 2018-07-16 at 4 01 42 pm](https://user-images.githubusercontent.com/15315514/42780571-9384fdba-8911-11e8-83d0-71cc2be77ce4.png)

**Comment by Willv19** [comment]
I believe that the issue should be resolved by fixing this ticket on the backend: https://github.com/AlexsLemonade/refinebio/issues/384

**Comment by Miserlou** [comment]
Yeah, this should be fixed already but I'm waiting for the API to redeploy before I close this issue.

**Comment by Miserlou** [comment]
Resolved.
