### ISSUE TITLE
Fix Favicon

### ISSUE THREAD

**Issue by Willv19** [AlexsLemonade/refinebio-frontend#172]
The favicon in the frontend code is currently this default react favicon:
![favicon 1](https://user-images.githubusercontent.com/13942258/42895703-aaa2264e-8a88-11e8-9990-a7138e42a778.png)

We probably want it to match the current refine.bio landing page, which has this favicon:
![favicon](https://user-images.githubusercontent.com/13942258/42895709-af30e308-8a88-11e8-8e3f-2a8b137a1c06.png)

**Comment by Miserlou** [comment]
DUPE https://github.com/AlexsLemonade/refinebio-frontend/issues/103
