### ISSUE TITLE
Filters change based on filtered results isn't correct

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#185]
When the user adds a filter to the search results, ALL filters are reloaded and only the filters applicable on the filtered results is visible. This limits how users can filter. 

For example, say the user wants to filter results based on human AND mouse. They cannot do that with the way filtering currently behaves. When they choose mouse, all filters are reloaded based on the filtered results, taking away the option to also filter by Human.

Before applying a filter:
![screen shot 2018-07-23 at 4 13 32 pm](https://user-images.githubusercontent.com/15315514/43100634-f05560fc-8e93-11e8-9d6d-c1e197fa6a99.png)

After:
![screen shot 2018-07-23 at 4 13 40 pm](https://user-images.githubusercontent.com/15315514/43100635-f3e2aa4a-8e93-11e8-9d42-8ab855a33e33.png)

Expected Behavior:
In the above example, when user applies the filter on organism, the filter options should change for Technology and Publication but all options should remain for Organism.

**Comment by Willv19** [comment]
I looked into this in the code, and it looks like in the frontend we are just rendering whatever filters we get back from the backend. I will make an issue there for the fix.
