### ISSUE TITLE
Line height and platform format in factoid bar isn't consistent

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#186]
The line height for platform in the factoid bar on search page is 1:
![screen shot 2018-07-23 at 4 34 27 pm](https://user-images.githubusercontent.com/15315514/43101389-4ae6e73c-8e96-11e8-8b15-a95132c94e8f.png)

The line height for platform in the factoid bar on experiment page is 1.5:
![screen shot 2018-07-23 at 4 34 19 pm](https://user-images.githubusercontent.com/15315514/43101422-5d389368-8e96-11e8-95d0-7cf6012cedfc.png)

It should be consistently 1.5

Also, the platform name isn't consistently formatted.

**Comment by Willv19** [comment]
Reliant on https://github.com/AlexsLemonade/refinebio/pull/454 landing
