### ISSUE TITLE
Download Page Is Extremely Slow for Large Datasets

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#192]
This may be a backend issue, or it may be a frontend-not-using-the-API-properly issue.

Building a very large (>1000 samples) dataset causes the download page to take an extremely long time to render. Looking at the request logs, it looks like this is because we are making some gigantic requests to the API, such as [this monstrosity](https://api.staging.refine.bio/samples/?limit=1000000000000000&accession_codes=GSM2262187,GSM2261806,GSM2261557,GSM2261702,GSM2261817,GSM2261546,GSM2261559,GSM2261547,GSM2261954,GSM2261801,GSM2261614,GSM2261677,GSM2262120,GSM2262024,GSM2262030,GSM2261753,GSM2261592,GSM2262277,GSM2262168,GSM2261756,GSM2261893,GSM2261683,GSM2261615,GSM2261846,GSM2261745,GSM2261868,GSM2261642,GSM2261867,GSM2262151,GSM2262153,GSM2261967,GSM2261968,GSM2262079,GSM2261972,GSM2262038,GSM2261964,GSM2261727,GSM2261897,GSM2261562,GSM2261805,GSM2262301,GSM2262010,GSM2261554,GSM2262195,GSM2262222,GSM2261767,GSM2261875,GSM2262274,GSM2262241,GSM2261943,GSM2261812,GSM2261755,GSM2261853,GSM2262116,GSM2262063,GSM2262148,GSM2261762,GSM2261987,GSM2262017,GSM2262282,GSM2262200,GSM2261995,GSM2261687,GSM2261999,GSM2262272,GSM2261911,GSM2262143,GSM2262287,GSM2261738,GSM2261740,GSM2261803,GSM2261658,GSM2261576,GSM2262130,GSM2261824,GSM2261836,GSM2261757,GSM2262126,GSM2262197,GSM2261955,GSM2261640,GSM2261586,GSM2262202,GSM2262308,GSM2261785,GSM2262174,GSM2261795,GSM2261799,GSM2262182,GSM2261877,GSM2262190,GSM2261696,GSM2261729,GSM2261710,GSM2261747,GSM2261735,GSM2262215,GSM2262015,GSM2261885,GSM2261650,GSM2261553,GSM2261569,GSM2262020,GSM2261830,GSM2262220,GSM2261963,GSM2262080,GSM2262060,GSM2262297,GSM2261538,GSM2261818,GSM2261914,GSM2262275,GSM2261603,GSM2262273,GSM2261918,GSM2262214,GSM2261760,GSM2262267,GSM2262179,GSM2261686,GSM2261778,GSM2262165,GSM2262237,GSM2262085,GSM2261880,GSM2262008,GSM2262119,GSM2261721,GSM2262103,GSM2261823,GSM2262300,GSM2261895,GSM2262242,GSM2262027,GSM2261613,GSM2262076,GSM2261563,GSM2261618,GSM2261598,GSM2262072,GSM2262201,GSM2261797,GSM2262089,GSM2261979,GSM2261807,GSM2262288,GSM2262128,GSM2261861,GSM2261783,GSM2261769,GSM2262064,GSM2262122,GSM2262032,GSM2261607,GSM2261587,GSM2262044,GSM2261851,GSM2262230,GSM2261971,GSM2262084,GSM2261583,GSM2262256,GSM2262232,GSM2261905,GSM2262139,GSM2262014,GSM2261739,GSM2261579,GSM2262141,GSM2261882,GSM2262011,GSM2262134,GSM2262029,GSM2261636,GSM2261961,GSM2261722,GSM2262280,GSM2262185,GSM2261901,GSM2261976,GSM2262050,GSM2262250,GSM2261828,GSM2261788,GSM2261697,GSM2261913,GSM2262176,GSM2262227,GSM2262205,GSM2261726,GSM2262110,GSM2262102,GSM2261688,GSM2262186,GSM2261689,GSM2261839,GSM2261825,GSM2262137,GSM2262263,GSM2261838,GSM2261953,GSM2262105,GSM2261977,GSM2262095,GSM2262159,GSM2261886,GSM2261894,GSM2261661,GSM2262023,GSM2262035,GSM2262006,GSM2261916,GSM2261585,GSM2262260,GSM2262136,GSM2261827,GSM2261653,GSM2262152,GSM2262039,GSM2261773,GSM2261992,GSM2261682,GSM2261780,GSM2262257,GSM2261560,GSM2261656,GSM2261550,GSM2262253,GSM2261865,GSM2262000,GSM2261574,GSM2261679,GSM2262231,GSM2262291,GSM2262113,GSM2262104,GSM2261970,GSM2262149,GSM2262312,GSM2261651,GSM2261884,GSM2261973,GSM2261699,GSM2262233,GSM2261804,GSM2262033,GSM2261544,GSM2262289,GSM2261959,GSM2262191,GSM2261835,GSM2261958,GSM2262083,GSM2261765,GSM2262055,GSM2261920,GSM2261597,GSM2261965,GSM2262056,GSM2262065,GSM2261701,GSM2261708,GSM2262223,GSM2261627,GSM2262099,GSM2262012,GSM2262121,GSM2261856,GSM2262093,GSM2262081,GSM2261668,GSM2261937,GSM2262229,GSM2261844,GSM2262239,GSM2261692,GSM2262166,GSM2261629,GSM2261748,GSM2261847,GSM2261578,GSM2261595,GSM2261859,GSM2262088,GSM2261815,GSM2262108,GSM2262228,GSM2262279,GSM2261821,GSM2261870,GSM2262310,GSM2261750,GSM2261657,GSM2261742,GSM2261601,GSM2261763,GSM2261772,GSM2262043,GSM2261781,GSM2261716,GSM2261900,GSM2262155,GSM2262181,GSM2261881,GSM2262203,GSM2261695,GSM2262071,GSM2261713,GSM2262123,GSM2261567,GSM2261879,GSM2262092,GSM2261676,GSM2261573,GSM2261565,GSM2261718,GSM2261842,GSM2262061,GSM2261876,GSM2261561,GSM2261624,GSM2261588,GSM2262171,GSM2262173,GSM2262183,GSM2261787,GSM2262265,GSM2262284,GSM2261652,GSM2261663,GSM2261684,GSM2262306,GSM2261860,GSM2262251,GSM2261917,GSM2262281,GSM2261949,GSM2261551,GSM2261923,GSM2261908,GSM2261883,GSM2262051,GSM2261924,GSM2261855,GSM2261930,GSM2262167,GSM2261832,GSM2261816,GSM2262236,GSM2261620,GSM2261998,GSM2261984,GSM2261681,GSM2261896,GSM2261608,GSM2262294,GSM2262255,GSM2261852,GSM2262086,GSM2262246,GSM2262074,GSM2261794,GSM2261674,GSM2262271,GSM2261858,GSM2261643,GSM2261910,GSM2262196,GSM2262107,GSM2262248,GSM2262156,GSM2261564,GSM2261709,GSM2262219,GSM2262005,GSM2262040,GSM2261927,GSM2261715,GSM2262178,GSM2262150,GSM2261777,GSM2262114,GSM2261541,GSM2261638,GSM2261811,GSM2262087,GSM2261610,GSM2261766,GSM2261864,GSM2262090,GSM2262026,GSM2262057,GSM2261771,GSM2261789,GSM2261800,GSM2261633,GSM2261558,GSM2262019,GSM2262243,GSM2262028,GSM2261983,GSM2261808,GSM2262154,GSM2261628,GSM2261673,GSM2261724,GSM2262302,GSM2261764,GSM2262249,GSM2262209,GSM2261887,GSM2261902,GSM2261639,GSM2262022,GSM2261725,GSM2261549,GSM2261904,GSM2261703,GSM2261719,GSM2261786,GSM2262049,GSM2261665,GSM2261555,GSM2261892,GSM2261678,GSM2262285,GSM2261814,GSM2262216,GSM2262054,GSM2261956,GSM2261833,GSM2261706,GSM2262254,GSM2261609,GSM2261775,GSM2261925,GSM2261631,GSM2262131,GSM2262058,GSM2261982,GSM2261906,GSM2261711,GSM2262192,GSM2262235,GSM2261548,GSM2261903,GSM2262244,GSM2261822,GSM2261849,GSM2262268,GSM2261582,GSM2262217,GSM2262106,GSM2261749,GSM2261566,GSM2262034,GSM2261933,GSM2261890,GSM2261552,GSM2261666,GSM2261705,GSM2261733,GSM2262269,GSM2262109,GSM2261935,GSM2261626,GSM2261593,GSM2262078,GSM2261694,GSM2261744,GSM2261873,GSM2261752,GSM2261616,GSM2262213,GSM2261802,GSM2262002,GSM2262210,GSM2261732,GSM2262052,GSM2261941,GSM2261655,GSM2261604,GSM2262292,GSM2261575,GSM2261605,GSM2262169,GSM2261809,GSM2261779,GSM2261891,GSM2262067,GSM2261543,GSM2261980,GSM2262146,GSM2262270,GSM2262117,GSM2261912,GSM2261641,GSM2261862,GSM2261671,GSM2261621,GSM2262036,GSM2262037,GSM2261746,GSM2261796,GSM2262070,GSM2261945,GSM2261997,GSM2261556,GSM2262129,GSM2262075,GSM2261981,GSM2261741,GSM2262225,GSM2262163,GSM2261667,GSM2261841,GSM2261969,GSM2262266,GSM2261759,GSM2261728,GSM2261829,GSM2261790,GSM2261798,GSM2262276,GSM2261693,GSM2261978,GSM2261580,GSM2262198,GSM2262172,GSM2262177,GSM2261776,GSM2262188,GSM2262132,GSM2262238,GSM2261632,GSM2261975,GSM2261659,GSM2261926,GSM2262082,GSM2262073,GSM2261660,GSM2262047,GSM2262046,GSM2262001,GSM2261731,GSM2261915,GSM2262003,GSM2262245,GSM2262042,GSM2261985,GSM2262189,GSM2261928,GSM2262264,GSM2261863,GSM2261996,GSM2261966,GSM2261690,GSM2261704,GSM2262066,GSM2261871,GSM2262258,GSM2261584,GSM2261848,GSM2262218,GSM2262194,GSM2262115,GSM2261878,GSM2262158,GSM2261737,GSM2261831,GSM2262041,GSM2261619,GSM2261596,GSM2262305,GSM2261594,GSM2261850,GSM2262290,GSM2261600,GSM2261717,GSM2261647,GSM2262101,GSM2261581,GSM2262144,GSM2261909,GSM2262164,GSM2261874,GSM2261568,GSM2262204,GSM2262247,GSM2261813,GSM2261714,GSM2261662,GSM2262004,GSM2262127,GSM2261899,GSM2261837,GSM2262224,GSM2262018,GSM2261539,GSM2261761,GSM2261680,GSM2262299,GSM2261602,GSM2261542,GSM2262261,GSM2262311,GSM2261540,GSM2261939,GSM2261617,GSM2261791,GSM2261754,GSM2262007,GSM2261991,GSM2261589,GSM2262184,GSM2261921,GSM2261670,GSM2262295,GSM2261611,GSM2262226,GSM2261590,GSM2261644,GSM2261646,GSM2261834,GSM2261712,GSM2261669,GSM2262045,GSM2261898,GSM2261819,GSM2262097,GSM2262125,GSM2261698,GSM2261723,GSM2262170,GSM2261946,GSM2261685,GSM2262207,GSM2261730,GSM2262313,GSM2262180,GSM2261792,GSM2261672,GSM2261720,GSM2261840,GSM2261907,GSM2262094,GSM2262157,GSM2262048,GSM2261793,GSM2262199,GSM2261774,GSM2262208,GSM2262160,GSM2261630,GSM2262135,GSM2261691,GSM2261826,GSM2261889,GSM2262053,GSM2262307,GSM2262013,GSM2261599,GSM2262077,GSM2261736,GSM2261845,GSM2262286,GSM2262262,GSM2262175,GSM2262278,GSM2261820,GSM2261758,GSM2261743,GSM2262162,GSM2261700,GSM2261622,GSM2262240,GSM2261649,GSM2262016,GSM2261869,GSM2261634,GSM2262296,GSM2261962,GSM2262138,GSM2261872,GSM2261637,GSM2262133,GSM2262021,GSM2262298,GSM2261664,GSM2262031,GSM2262145,GSM2261734,GSM2261635,GSM2262111,GSM2262252,GSM2262069,GSM2261922,GSM2261989,GSM2261751,GSM2261888,GSM2262211,GSM2261957,GSM2262140,GSM2262283,GSM2261866,GSM2261648,GSM2262234,GSM2261843,GSM2261606,GSM2261707,GSM2262212,GSM2262068,GSM2261974,GSM2261986,GSM2261810,GSM2261994,GSM2262112,GSM2262304,GSM2261854,GSM2261623,GSM2261951,GSM2262096,GSM2262303,GSM2261770,GSM2261572,GSM2262309,GSM2262193,GSM2261857,GSM2261571,GSM2262091,GSM2262025,GSM2262161,GSM2261784,GSM2261645,GSM2261960,GSM2262147,GSM2262098,GSM2262124,GSM2261570,GSM2261919,GSM2262142,GSM2262062,GSM2261654,GSM2262009,GSM2262293,GSM2261990,GSM2261988,GSM2262059,GSM2261577,GSM2261591,GSM2261612,GSM2261782,GSM2261768,GSM2261993,GSM2261545,GSM2262206,GSM2262221,GSM2262100,GSM2262259,GSM2261625,GSM2261675,GSM2262118).

which returns 4MB of response after 16 seconds.

Why is this call needed at all? It appears that individual samples are re-requested on the sample detail pop up view, so it isn't for that. If there are other statistics that are required, perhaps we could instead add that to the dataset endpoint rather than require these massive requests so they can be calculated in the browser. 

Or, perhaps this call isn't required at all. 

@Willv19 - you've now got the most experience with this page, any thoughts?

**Comment by Willv19** [comment]
I think the solution to this issue lies primarily in the backend. The monstrosity of a request is made for these two method calls: getExperimentCountBySpecies and groupSamplesBySpecies. If we could add the functionality of these two methods to the backend it should reduce latency dramatically.

**Comment by arielsvn** [comment]
closing with https://github.com/AlexsLemonade/refinebio-frontend/pull/236
