### ISSUE TITLE
Add transformation dropdown menu on downloads page

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#208]
Users should have the following transformation options:

- No transformation
- Z-score (`STANDARD`)
- [0,1] (`MINMAX`)

**Comment by Miserlou** [comment]
I think these should only be added if there is corresponding documentation, either a modal or a little hover thingy explaining what these mean and what they actually do.

**Comment by cgreene** [comment]
Transformations are included in https://github.com/AlexsLemonade/refinebio/issues/450, so there will be docs.

**Comment by cgreene** [comment]
@dvenprasad : What are your thoughts on how to most effectively get the information from the docs to people?

**Comment by dvenprasad** [comment]
![screen shot 2018-08-01 at 11 22 19 am](https://user-images.githubusercontent.com/15315514/43531154-3546ad84-957d-11e8-8156-44c26a652324.png)

Link the ? icon to docs. 

Invision: [https://invis.io/9SNAJ70ME4D#/312072856_download-Dataset-Download-Option-Help](https://invis.io/9SNAJ70ME4D#/312072856_download-Dataset-Download-Option-Help)

The help button is in Assets/Images/Badges on InVision
@Willv19  let me know if you have trouble finding things.

**Comment by Willv19** [comment]
Relies on https://github.com/AlexsLemonade/refinebio/issues/469
