### ISSUE TITLE
Share Download Page Remove All Button

### ISSUE THREAD

**Issue by Willv19** [AlexsLemonade/refinebio-frontend#216]
Currently, on the "Share Download" page the "Remove All" button is present and active, but clicking it does nothing. The button should be disabled to make it clear that this is a separate dataset that is immutable.

**Comment by dvenprasad** [comment]
Do you think it would be possible to change the title from 'Download Dataset' to 'Shared Dataset'? It would help in making that distinction between their dataset and one that is shared.

![screen shot 2018-08-02 at 11 07 50 am](https://user-images.githubusercontent.com/15315514/43592800-5657cc7a-9644-11e8-8ea9-2b36bdd0b566.png)

**Comment by Willv19** [comment]
Yeah, that should be easy
