### ISSUE TITLE
Experiment Page: Add processing information modals

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#22]
## Description
When user clicks on the link in the "Processing Information" column in the samples table, they should get a modal that displays all the processing information associated with that sample.

### refine.bio processed with 1 middle step
![screen shot 2018-05-18 at 2 25 22 pm](https://user-images.githubusercontent.com/4724065/40251475-6c643b6c-5aa7-11e8-9283-a5822b9a5aa4.png)
### refine.bio processed with 2 middle steps
![screen shot 2018-05-18 at 2 26 43 pm](https://user-images.githubusercontent.com/4724065/40251529-85bbeaec-5aa7-11e8-9b6d-d9ab5dc1659a.png)
### submitter processed
![screen shot 2018-05-18 at 2 26 23 pm](https://user-images.githubusercontent.com/4724065/40251528-85af355e-5aa7-11e8-9f4c-f9785f48df09.png)

**Comment by ramenhog** [comment]
@Miserlou correct me if I'm wrong, but we don't get this info from the `samples` endpoint yet right?

**Comment by cgreene** [comment]
My impression is that this isn't landing until after Keytar Kurt. It looks like it will depend at least on https://github.com/AlexsLemonade/refinebio/issues/101 which is not in the Keytar milestone.

**Comment by jaclyn-taroni** [comment]
I would argue that it requires the copy on #170

**Comment by cgreene** [comment]
Oh! Spiffy! Then is https://github.com/AlexsLemonade/refinebio/issues/101 going to be different than what is in https://github.com/AlexsLemonade/refinebio/issues/170?

**Comment by arielsvn** [comment]
Ok, I'll remove this issue from the Keytar Kurt milestone.

**Comment by jaclyn-taroni** [comment]
I'm imagining that it will be a bit more comprehensive in that it will include links to repositories where we've done bits of analysis, etc.

**Comment by ramenhog** [comment]
Ok, just to confirm, we don't need to worry about showing any processing information for Keytar Kurt?

**Comment by jaclyn-taroni** [comment]
> we don't need to worry about showing any processing information for Keytar Kurt?

I think we do, because we have the copy needed. What do you think @cgreene?

**Comment by cgreene** [comment]
Actually, I got confused by a separate issue that I've been watching in the waffle. It looks like there is enough information in https://github.com/AlexsLemonade/refinebio/issues/170 to do a first iteration of this page.

**Comment by jaclyn-taroni** [comment]
I believe this is also related (package versions, etc): AlexsLemonade/refinebio#229

**Comment by arielsvn** [comment]
Tagging @Miserlou, we just spoke about this... One solution we discussed was adding a field to the Sample Details, that contains information of the pipeline that was used.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/pull/299 Adds a `pipelines` field to each sample. This field will be an array of strings with the following possible values:

1. Submitter-processed
2. Affymetrix SCAN
3. Salmontools
4. Agilent SCAN TwoColor
5. Illumina SCAN
6. tximport
7. Salmon
8. MultiQC

@Miserlou had the idea of showing multiple values in the Processing Information field, for the samples that have more than one pipeline.

**Comment by arielsvn** [comment]
We talked about this issue, and for **Keytar Kurt** these are the possible values of `pipeline` for which we'll be able to show information.

- `['Submitter-processed']`
- `['Affymetrix SCAN']`
- `['Illumina SCAN']`
- `['tximport', 'Salmon']`

For the others, if they appear, we'll just show the text on the Processing Information column.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/pull/50 Adds the processing information dialogs, but the package version information is static until the endpoints are exposed on the backend. AlexsLemonade/refinebio#229

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/pull/50 Added the last two processing information modals that we planned. Now we need to add version information. I opened #65 to keep track of that, so I'm closing this issue.
