### ISSUE TITLE
Download Link Goes to `undefined/undefined`

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#226]
To repro, smash a jorb and wait for it to be delivered. View the dataset page and click the button.

![screen shot 2018-08-07 at 3 06 42 pm](https://user-images.githubusercontent.com/139987/43796923-ac13ac02-9a53-11e8-947e-abb0559e732c.png)
![screen shot 2018-08-07 at 3 06 45 pm](https://user-images.githubusercontent.com/139987/43796925-ae68d7d4-9a53-11e8-8c1b-d2dc1f7b2d4a.png)

I know the dataset is actually available though because the download delivered from the email worked.

**Comment by arielsvn** [comment]
I haven't been able to completely reproduce this. On staging the dataset is always market as `is_processing = true` even though I got the email with the download link.

However, in the front end we build that download link using the values `s3_bucket` and `s3_key`, returned by the dataset details endpoint.

In [this sample](https://api.staging.refine.bio/dataset/72f53239-8181-4ae8-9545-8b2054775a30/) I got the email with the correct download link, but both `s3_bucket` and `s3_key` are empty. @Miserlou that's probably why you were redirected to that url.

Is this a case we should handle? Or is it an error in the response?
