### ISSUE TITLE
Experiment Page: display correct fields in samples table

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#23]
## Description
Display the fields we want as columns in the samples table.

**Relies on:** https://github.com/AlexsLemonade/refinebio/pull/252

**Comment by ramenhog** [comment]
@Miserlou it looks like the backend PR this was relying on is merged. We should have everything we need on the frontend to render those fields in the table right?

**Comment by cgreene** [comment]
Regarding order, I would likely go most complete within whatever is currently being viewed -> least complete.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/pull/48 Connected the table with the correct fields, but there we're doing a single request for each Sample to fetch their details, and sorting on the table doesn't work.

This can be solved with https://github.com/AlexsLemonade/refinebio/pull/298 which extended the Samples List endpoint to to return detailed information about the samples. 

I'll integrate this in a new PR.
