### ISSUE TITLE
Display Sample annotations and indicate corrected UI fields

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#242]
This id the front-end ticket for https://github.com/AlexsLemonade/refinebio/issues/532. 

Based on on conversations on https://github.com/AlexsLemonade/refinebio/issues/515 and #215, the UI will need to display:
- Add a column to the samples table 'Additional Metadata' and link out to be able view sample annotations in a modal
-  a little note indicating that some fields maybe corrected

![screen shot 2018-08-17 at 9 21 01 am](https://user-images.githubusercontent.com/15315514/44268272-f2149380-a1fe-11e8-840e-46e5d440908c.png)

![screen shot 2018-08-17 at 9 21 20 am](https://user-images.githubusercontent.com/15315514/44268275-f640b100-a1fe-11e8-8508-5b98a0a156bf.png)

**Comment by dongbohu** [comment]
@dvenprasad Do you have a svg file for the small `information` icon on the left of the text "Included in Download"? I searched the source code but didn't find it.

**Comment by dvenprasad** [comment]
Yep. I can slack it to you.

**Comment by dvenprasad** [comment]
@dongbohu  In terms of functionality, it looks good to me. I have few  comments:
- On experiment page, we need to add a footnote below the samples table saying some samples maybe harmonized, like this: 
![screen shot 2018-08-20 at 11 41 17 am](https://user-images.githubusercontent.com/15315514/44350682-fd212b00-a46d-11e8-8b1c-f621fb0ab755.png)

- On the modal, would it be possible to wrap text so user won't have to scroll horizontally?

- Could we add the scrollbar for the text area rather than using the scrollbar for the page? 

- This needs to be centered 👇 
![screen shot 2018-08-20 at 11 43 37 am](https://user-images.githubusercontent.com/15315514/44350848-5db06800-a46e-11e8-8bf4-958435df3266.png)

- Is it possible to style the text area like the mockup? If color coding the values isn't possible, let the font color be #FDFDFD

**Comment by dongbohu** [comment]
@dvenprasad: Thanks for your comments. On the main page's footnote, is `Learn more` supposed to show another modal? If yes, what information should be shown on the modal?

**Comment by dvenprasad** [comment]
Learn more is supposed to linked to the docs. We don't have a specific link for that yet.

**Comment by dongbohu** [comment]
Okay, I will put a placeholder there for now.

**Comment by dongbohu** [comment]
@dvenprasad, please take a look at the web UI agian:
http://localhost:3000/experiments/2?ref=search
I think the only thing that is missing now is the syntax highlighting of the JSON code.

**Comment by dvenprasad** [comment]
It looks good to me! Just minor changes (for consistency and readability) 

- These need to be aligned such that their centers are aligned 
![screen shot 2018-08-21 at 4 51 40 pm](https://user-images.githubusercontent.com/15315514/44467234-55803600-a5f0-11e8-9541-8c2ec9ebc6cf.png)
![screen shot 2018-08-21 at 4 51 32 pm](https://user-images.githubusercontent.com/15315514/44467235-55803600-a5f0-11e8-887c-b0e709d6e2ce.png)

- Could we have a little margin between the sides of the text area and the text, so when it wraps it doesn't look like part of it is cut off?

![screen shot 2018-08-21 at 4 52 21 pm](https://user-images.githubusercontent.com/15315514/44467314-91b39680-a5f0-11e8-904b-4a197255e98b.png)


- The padding on the modal needs to be 56px to be consistent with the other modal. I've annotated the screenshot below with the spacings. 

![artboard](https://user-images.githubusercontent.com/15315514/44468489-5070b600-a5f3-11e8-939c-04dc3bc003f9.png)

**Comment by dvenprasad** [comment]
No, horizontally. Like below, where the centers of both badge and text are on the straight line

![screen shot 2018-08-22 at 10 29 57 am](https://user-images.githubusercontent.com/15315514/44469852-5d42d900-a5f6-11e8-8e7c-70007ff888ea.png)

**Comment by dongbohu** [comment]
Yes, that was what I meant. Thanks.

**Comment by dongbohu** [comment]
@dvenprasad, please check again:
http://165.123.67.202:3000/experiments/2?ref=search
Thanks.

**Comment by dvenprasad** [comment]
LGTM 👍

**Comment by dongbohu** [comment]
Closed by https://github.com/AlexsLemonade/refinebio-frontend/pull/261
