### ISSUE TITLE
Search by author as an example search term on the landing page?

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#243]
Since refine.bio can now support search by author, could we have an author show up as an example along with 'Notch, Medulloblastoma, and GSE16476'. 

Tagging @jaclyn-taroni for input.

**Comment by jaclyn-taroni** [comment]
https://www.ebi.ac.uk/arrayexpress/search.html?query=Versteeg&pagesize=25
