### ISSUE TITLE
Sorting on Samples Table toggles only between two states

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#248]
Sorting toggles between ascending and descending. Once someone sorts, there's no to get back to the default state, short of refreshing the page. 

Recommendation:
It should toggle between ascending, descending, and default.

**Comment by arielsvn** [comment]
When trying to implement this, I found a bug in the [table component](https://github.com/react-tools/react-table) that we use.

The table makes two requests to the backend to fetch the samples, and shows either one of the results depending on which request finish last. I filed an issue on the project https://github.com/react-tools/react-table/issues/1099 and will keep investigating.

Implemented the changes here https://github.com/AlexsLemonade/refinebio-frontend/compare/arielsvn/support/248-samples-table-sorting
