### ISSUE TITLE
Create Processing Information dialogs dynamically

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#249]
From https://github.com/AlexsLemonade/refinebio-frontend/pull/240/files/2b5ac464ea6bfd9da48b792e8ab3445af5f9e35f#r210742381

> With the introduction of Processor introduced in each ComputationalResult record, this variable may have to be updated. See:
https://github.com/AlexsLemonade/refinebio/blob/2e48ea9b16d2b5a3b0ffa074d28052800a746571/common/data_refinery_common/models/models.py#L410
We probably should figure out a better way to synchronize these constants than hardcoded strings. Can you file a new issue to keep track of it? Thanks.

All of the information regarding the Pipelines and the Processing information dialogs is stored statically in the front-end. With the introduction of `Processor` we might also be able to build these dialogs dynamically. I have to look more into this to see how it could be done.

This api endpoint https://github.com/AlexsLemonade/refinebio-frontend/issues/99#issuecomment-413269352 will probably be helpful.

**Comment by dvenprasad** [comment]
@arielsvn thinks that this is probably related.

Processing info is not linked for RNA-seq experiments
![screen shot 2018-08-17 at 3 47 29 pm](https://user-images.githubusercontent.com/15315514/44286434-15f3cb80-a237-11e8-8b96-909490a5cfca.png)

**Comment by arielsvn** [comment]
Given that we might have different types of pipelines for each sample, I think it would be good to rewrite the processing information dialogs, and generate them dynamically. Right now they are static and only support four types https://github.com/AlexsLemonade/refinebio-frontend/issues/22#issuecomment-394408631.

I updated the title of this issue accordingly.
