### ISSUE TITLE
Users can't sort the Add/Remove column

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#254]
If there are 150 samples in an experiment and they've already 3 samples, there's no way they can find those samples apart going each page of the samples table. 

Recommendation:
Allow users to sort the add/remove column.

**Comment by dvenprasad** [comment]
@arielsvn  I'm okay with the checkbox. We can figure out a different solution after testing, if needed. 
Since we have the checkbox, would it be possible to remove the sort buttons from 'Add/Remove' table header?

![screen shot 2018-08-28 at 10 14 12 am](https://user-images.githubusercontent.com/15315514/44729252-66c3b980-aaac-11e8-9913-b093a66e6fce.png)


Annotated:
![screen shot 2018-08-28 at 10 26 01 am](https://user-images.githubusercontent.com/15315514/44729440-d043c800-aaac-11e8-9530-dd4b91b068b8.png)

**Comment by arielsvn** [comment]
> Since we have the checkbox, would it be possible to remove the sort buttons from 'Add/Remove' table header?

Sure, we can do this.
