### ISSUE TITLE
The giant ticket of minor inconsistencies and bugs

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#255]
### 1
- [x] **Link Styling is inconsistent**
      - Remove underline from all links
      - Underline only on hover
      - "Remove" and "Clear all", "Clear Filters" are text buttons, leave them underlined.

--------------
### 2
- [x]  **Footer social icons don't have states**
Add hover states: Github
![screen shot 2018-08-15 at 2 17 20 pm](https://user-images.githubusercontent.com/15315514/44283856-aa593080-a22d-11e8-8763-a6e085cf5754.png)

Twitter
![screen shot 2018-08-15 at 2 16 14 pm](https://user-images.githubusercontent.com/15315514/44283874-b644f280-a22d-11e8-99c0-be90bb71c47c.png)

----------------

### 3
- [ ] **Platform badges don't change based on technology**

The platform badges should change based on the technology
For microarray: 
![screen shot 2018-08-15 at 2 44 40 pm](https://user-images.githubusercontent.com/15315514/44283995-0d4ac780-a22e-11e8-91e4-121b562a40f3.png)

For RNA-seq:
![screen shot 2018-08-15 at 2 45 30 pm](https://user-images.githubusercontent.com/15315514/44284002-150a6c00-a22e-11e8-8ebb-f569e7a53a51.png)

------------------
### 4
- [x] **Hover state of black ghost buttons are blue. It should be black**
The download page uses black ghost buttons for 'Remove' and 'Remove all'. On hover, the buttons have blue fill. They should have a black fill.

--------------------

### 5
- [x]  **Populate cells with no data with N/A** 

Cells with no data are currently left blank. Populate them with N/A
Styling: color: #9B9B9B, itlaics
![screen shot 2018-08-17 at 3 03 00 pm](https://user-images.githubusercontent.com/15315514/44284166-a7127480-a22e-11e8-813c-56fd4450f073.png)

----------------------

### 6
- [x] **Landing page: Increase font size on search button to 18px**

-----------------------

### 7
- [x] **Landing Page: Increase font size of .'Try searching for' on the landing page to 22px**

-----------------------

### 8
- [x] **Landing Page: Add a little blurb below sign up for updates to add more context**
Blurb: "Be the first to know about new features, compendia releases, and more!"
Font size: 22px; Spacing 16px above and below.

![screen shot 2018-08-17 at 3 13 27 pm](https://user-images.githubusercontent.com/15315514/44284560-1f2d6a00-a230-11e8-84be-a4a0f9edb5a6.png)

------------------------

### 9
- [x] **Download Page: Add a tool tip on hover for the ? on Aggregate and Transform**

On hover, have tool tip that says "What is this?" 

---------------------

### 10
- [x] **Download Page: On experiments view, link the experiment title to the experiment page.**

---------------

### 11
- [x] **Download Page: On experiments view, add 'Samples' after the number of samples.**

Current:
![screen shot 2018-08-16 at 11 31 00 am](https://user-images.githubusercontent.com/15315514/44284685-92cf7700-a230-11e8-99b1-ad78f5a4013e.png)

Expected:
![screen shot 2018-08-16 at 11 31 19 am](https://user-images.githubusercontent.com/15315514/44284688-97942b00-a230-11e8-9e2f-01aca9f01730.png)

**Comment by arielsvn** [comment]
Moved item 3 to https://github.com/AlexsLemonade/refinebio-frontend/issues/268
