### ISSUE TITLE
Downloads Page: Start Download and "Download Started" page

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#27]
## Description
* When user clicks "Download" on downloads page, start download and show them the "Download Started" page that allows them to enter their email when files are ready for download.

## Mockups
![screen shot 2018-05-18 at 2 49 52 pm](https://user-images.githubusercontent.com/4724065/40253093-77370b8c-5aac-11e8-8378-1100b343fb22.png)

**Comment by arielsvn** [comment]
We discussed the possibility of having an individual url for this page. Something like `/download/id`, where `id` identifies the download that the user started. Here we can fetch information about the specified download, and depending on it's state show:

- if the file is still being prepared, we can show the input above for the user to enter his email and be notified when the process ends
- if it's ready we can show the download link directly.
- if it's expired... show relevant information

**Comment by arielsvn** [comment]
After discussions related to #32, we decided to change the url of this page to `/dataset/:dataSetId`. This page will still show different content, as described in the previous comment, depending on the state of the dataset.

/cc @ramenhog @dvenprasad
