### ISSUE TITLE
Annotations are Shown Even When There Aren't Any

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#274]
![screen shot 2018-08-28 at 11 12 31 am](https://user-images.githubusercontent.com/139987/44732463-54994980-aab3-11e8-88af-0112213fac14.png)

Why there aren't any is another question..

**Comment by Miserlou** [comment]
We don't get sample-level annotations from SRA.

**Comment by dongbohu** [comment]
Fixed by PR #277.
