### ISSUE TITLE
Show error message when the download fails to start

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#286]
With https://github.com/AlexsLemonade/refinebio/pull/585 the request to start a dataset will fail, if there's an error queueing the job. We should display an error and maybe show a button to allow the user to go back to the downloads page and try again?

@dvenprasad what do you think?

**Comment by Miserlou** [comment]
I don't think it has to be much more than "Something went wrong, try again? If the problem persists, please contact ccdl@alexslemonade.com" and let them press the button again.

**Comment by arielsvn** [comment]
So, something like this? Maybe changing the image?

![screen shot 2018-09-05 at 1 20 07 pm](https://user-images.githubusercontent.com/1882507/45109769-79726a00-b10e-11e8-8392-8b564a5fe560.png)

**Comment by Miserlou** [comment]
LGTM

**Comment by jaclyn-taroni** [comment]
`ccdl@alexslemonade.org`

**Comment by arielsvn** [comment]
Closed by https://github.com/AlexsLemonade/refinebio-frontend/pull/283#issuecomment-419190702
