### ISSUE TITLE
Back to top button is above content on mobile and tablet

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#287]
@dvenprasad what do you think we should do with the Back to Top button in these cases??

![image](https://user-images.githubusercontent.com/1882507/45118366-4c31b600-b126-11e8-9a59-41624f9a1d79.png)

![image](https://user-images.githubusercontent.com/1882507/45118401-69668480-b126-11e8-96a7-863c6f3452cd.png)

**Comment by dvenprasad** [comment]
What about something like this? Place a small #f2f2f2 square below it with some shadowing. 
![screen shot 2018-09-05 at 4 51 03 pm](https://user-images.githubusercontent.com/15315514/45120429-11328100-b12c-11e8-8419-9e285bc52b19.png)

**Comment by arielsvn** [comment]
I like it! Let's do that!
