### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#313]
Before we launch, we'll need to link the frontend of refine.bio to our documentation (see: https://github.com/AlexsLemonade/refinebio-docs and https://refinebio-docs.readthedocs.io/en/latest/).

#### Next steps 

@dvenprasad will perform a walk through and post a list of all the spots on the front end where we will need to link to _specific_ sections of the docs.

**Comment by dvenprasad** [comment]
1. Experiment Page: Learn more should link to [refine.bio harmonized section](https://refinebio-docs.readthedocs.io/en/latest/main_text.html#refine-bio-harmonized-metadata) of the docs
Also present on samples table modal. 

![screen shot 2018-09-25 at 10 50 36 am](https://user-images.githubusercontent.com/15315514/46022576-e4c9af00-c0b0-11e8-96f0-7452d78a934e.png)

2. Processing Info modal: Link the badge to [refine.bio processed section](https://refinebio-docs.readthedocs.io/en/latest/main_text.html#refine-bio-processed-refinebio-processedibadge) of the docs
Similarly, link the submitter processed badge to [submitter processed section](https://refinebio-docs.readthedocs.io/en/latest/main_text.html#submitter-processed-submitter-processed-badge) of the docs.

![screen shot 2018-09-25 at 10 52 53 am](https://user-images.githubusercontent.com/15315514/46022779-3d00b100-c0b1-11e8-903e-32956238f160.png)

3. Downloads page: Links the (?) on Aggregate and Transform to [Aggregations](https://refinebio-docs.readthedocs.io/en/latest/main_text.html#aggregations) and [Transformations](https://refinebio-docs.readthedocs.io/en/latest/main_text.html#transformations) sections respectively.

![screen shot 2018-09-25 at 10 54 30 am](https://user-images.githubusercontent.com/15315514/46022928-8a7d1e00-c0b1-11e8-8c0b-ae63ef262027.png)

**Comment by dvenprasad** [comment]
Note: These links should open in a new tab.
