### ISSUE TITLE
Small cosmetic issues

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#323]
I'll add here any small cosmetic issues that we discover.

- [x] Underline in download button

![image](https://user-images.githubusercontent.com/1882507/46026728-1a26ca80-c0ba-11e8-889d-e8b242e0d03d.png)

- [x] Space on platforms

![image](https://user-images.githubusercontent.com/1882507/46026843-522e0d80-c0ba-11e8-814e-59bfbd8b4f24.png)

^ reported by @Miserlou

**Comment by Miserlou** [comment]
Whole page gets stretched by extremely long experiment title:

<img width="1792" alt="screen shot 2018-09-25 at 12 02 21 pm" src="https://user-images.githubusercontent.com/139987/46027051-e7310680-c0ba-11e8-98ed-8744d11ea319.png">
