### ISSUE TITLE
Add quantile normalization information to processing modal

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#330]
As stated in the [quantile normalization section](https://github.com/AlexsLemonade/refinebio-docs/blob/master/docs/main_text.md#quantile-normalization) of our documentation:

> Note that only gene expression matrices that we are able to successfully quantile normalize will be available for download.

As a result, all gene expression matrices delivered to a user will be quantile normalized. Although this is information is in our documentation, there is no indication of this on our processing modal at the moment. I think a short blurb is sufficient. Something like:

_All data available for download will be quantile normalized. For more information regarding how quantile normalization is performed and its limitations, see [our documentation](https://github.com/AlexsLemonade/refinebio-docs/blob/master/docs/main_text.md#quantile-normalization)._

@dvenprasad and @cgreene thoughts?

**Comment by Miserlou** [comment]
We also do have the ability to make this configurable.

**Comment by dvenprasad** [comment]
Invision link: https://invis.io/3KO61MK64GF#/321105286_experiment-Page-Processing-Info-AE


![experiment-page-processing-info-ae](https://user-images.githubusercontent.com/15315514/46158700-6dc91d80-c24c-11e8-8596-7a1a2d21517d.png)
