### ISSUE TITLE
Has Publication Doesn't Seem to Work Properly

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#339]
![screen shot 2018-09-28 at 12 26 35 pm](https://user-images.githubusercontent.com/139987/46220976-c3b7c700-c319-11e8-8b8d-04a0f17b4458.png)

**Comment by arielsvn** [comment]
For this case, we're showing the results returned by this url:

https://api.refine.bio/search/?search=zeb&limit=10&offset=0&technology=RNA-SEQ&has_publication=true

And sending `has_publication=true`, is this how it should be queried?

**Comment by arielsvn** [comment]
Also, Deepa noticed that for the term [hypoxia](https://www.refine.bio/results?q=hypoxia) we're not showing any filters under Publication:

![image](https://user-images.githubusercontent.com/1882507/46293519-c573cb80-c561-11e8-8350-e61392bb6aea.png)

[The api](https://api.refine.bio/search/?search=hypoxia&limit=10&offset=0) is not returning any publication filter for that query

![image](https://user-images.githubusercontent.com/1882507/46293678-331ff780-c562-11e8-8769-faf0830203e0.png)

**Comment by Miserlou** [comment]
I've added a change for this in this branch: https://github.com/AlexsLemonade/refinebio/tree/miserlou/haspub
But I'm worried that this implementation might have unintended consequences. Can you try it out before I create a PR?

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/pull/373/commits/4299e959f8233143e41bc2a6a8967182abd822b1 in #373 makes sure we don't display any empty groups of filters

**Comment by arielsvn** [comment]
Fixed with the last deploy

**Comment by arielsvn** [comment]
Seems that Has publication is not counting correctly all samples. Eg for [this page](https://www.refine.bio/results?filter_order=organisms__name&organisms__name=GALLUS_GALLUS) the 6 samples from the second result aren't counted and that experiment doesn't appear if `has_publication` is enabled.

![image](https://user-images.githubusercontent.com/1882507/49607556-4a190680-f964-11e8-9e78-bcd0676e072e.png)

**Comment by Miserlou** [comment]
Can you check if this regression was introduced by the recent "optimizations"

**Comment by arielsvn** [comment]
I think the problems with this filter might be related to some inconsistencies in the DB, where the field `has_publication` doesn't have the correct value. Take [this experiment](https://api.refine.bio/experiments/GSE18157/) for example.

![image](https://user-images.githubusercontent.com/1882507/49758987-5ec00c00-fc8e-11e8-8b2b-161aeb7cb274.png)

It has `has_publication=False` even though there's a publication associated with it. @Miserlou and @kurtwheeler any thoughts on what might have caused this.
