### ISSUE TITLE
Individual Pages Link to ID, Not Accession

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#346]
![screen shot 2018-09-28 at 2 59 53 pm](https://user-images.githubusercontent.com/139987/46228154-3bdcb780-c32f-11e8-9de8-7a761b1c7c3b.png)

**Comment by arielsvn** [comment]
I just notices that the API also uses the ID to get details on an experiment:

https://api.refine.bio/experiments/16/

Is this alright?

**Comment by arielsvn** [comment]
We could also use

https://api.refine.bio/experiments/?accession_code=SRP087617

But that doesn't return all the experiment's information.
