### ISSUE TITLE
Individual Pages Cannot Be Directly Accessed

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#347]
![screen shot 2018-09-28 at 3 00 35 pm](https://user-images.githubusercontent.com/139987/46228194-51ea7800-c32f-11e8-9d6c-04c486a70db4.png)

This is a huge problem, related: https://github.com/AlexsLemonade/refinebio-frontend/issues/346

**Comment by arielsvn** [comment]
Was this fixed? It seems to be working now:

![image](https://user-images.githubusercontent.com/1882507/46292135-24cfdc80-c55e-11e8-89c1-6e252d4220ba.png)

**Comment by Miserlou** [comment]
I can't reproduce this anymore. Not sure what happened in the meantime though.
