### ISSUE TITLE
Set Meta Tags On Frontpage and Individual Pages

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#349]
https://moz.com/blog/seo-meta-tags

**Comment by Miserlou** [comment]
Also: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by arielsvn** [comment]
For reference: [Lambda@Edge](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html) and sample code to make an [http request](https://stackoverflow.com/a/28455874/763705)

**Comment by arielsvn** [comment]
Meta descriptions suggested by the communications team:

> 1. Share individual experiment via Slack/email/Twitter DM. Audience: Scientists
> *Examine this experiment’s processed samples and add it to your own custom dataset.*
> 
> 2. Share landing/search page via Twitter. Audience: mostly scientists, some lay audience
> *Browse decades of harmonized childhood cancer data and build custom datasets to accelerate the pace of research.*
> 
> 3. Share landing/search page via Facebook. Audience: lay audience
> *Browse decades of harmonized childhood cancer data and discover how this multi-species repository accelerates the search for cures.*
> 
> 4. Share about page via Twitter/Facebook. Audience: lay audience
> *Learn how this collection of childhood cancer data gives researchers a powerful new tool to accelerate the search for cures.*
> 
> 5. Share custom dataset link via Slack/email/Twitter DM. Audience: scientists
> *Explore (and download?) this custom harmonized childhood cancer transcriptome dataset.*

We decided to have a single title/description for twitter/facebook for the entire site. I'll update https://github.com/AlexsLemonade/refinebio-frontend/pull/359 with these descriptions accordingly.
