### ISSUE TITLE
Redirect 403s to the error page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#354]
Currently this is our 403 page:
![screen shot 2018-10-02 at 9 28 47 am](https://user-images.githubusercontent.com/15315514/46351563-a9d1f900-c625-11e8-9bce-23dfb2338dfe.png)

Have it redirect to
![screen shot 2018-10-02 at 9 31 27 am](https://user-images.githubusercontent.com/15315514/46351703-fb7a8380-c625-11e8-8f93-cc310483f08b.png)

The copy needs to be modified and maybe add the sentry form if appropriate.

**Comment by arielsvn** [comment]
On what url did you get that request?

**Comment by arielsvn** [comment]
This was an error from cloudfront, the files in the front-end weren't being served. Users should get the error pages for any exceptions that are raised within the app.

Closing this...
