### ISSUE TITLE
Gene Identifier Conversion copy is shown for refine.bio-processed samples

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#355]
Samples only go through our gene identifier conversion pipeline when they are noop'd/are submitter-processed. This copy is displayed on the processing modal on refine.bio processed data where gene identifier conversion is not performed.

![screenshot from 2018-10-02 14-27-53](https://user-images.githubusercontent.com/19534205/46368997-a3f10d80-c64f-11e8-8ba3-cf7fd658ffde.png)

Have found that this is the case for the following samples: `GSM604803`, `GSM324904`, `GSM2027266`, `GSM1708647`

**Comment by Miserlou** [comment]
https://www.refine.bio/experiments/2?ref=search

There should also be a space between 2012. and DOI
