### ISSUE TITLE
Going directly to a page with `?ref=search` breaks Back to Results button

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#356]
Open a new tab and paste in https://www.refine.bio/experiments/2?ref=search

Click on Back to Results

expected: I go to the front page
reality: A new blank tab pops up

**Comment by arielsvn** [comment]
This will be fixed by https://github.com/AlexsLemonade/refinebio-frontend/pull/353, I removed the parameter `ref=search` from the url there.

**Comment by arielsvn** [comment]
closed by #353
