### ISSUE TITLE
Lack of spacing in RNA-seq platform display

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#362]
There are no spaces in the RNA-seq platforms when displayed.

![screenshot from 2018-10-04 09-44-46](https://user-images.githubusercontent.com/19534205/46478145-4d541280-c7ba-11e8-9b67-8f8001946cde.png)

![screenshot from 2018-10-04 09-45-05](https://user-images.githubusercontent.com/19534205/46478153-504f0300-c7ba-11e8-9768-60b5202f108b.png)

In these screenshots, I would expect to see `Illumina HiSeq 2500` and `Illumina HiSeq 2000`, respectively. We have "nicely formatted" platform names available here: https://github.com/AlexsLemonade/refinebio/blob/f7338df764e389dc81de04196a0dbc207b13be2b/config/supported_rnaseq_platforms.txt 

I'm not sure if this change should take place on the frontend or the backend.

**Comment by arielsvn** [comment]
In the front-end we're showing there the field `pretty_platforms` :https://github.com/AlexsLemonade/refinebio/blob/dev/api/data_refinery_api/serializers.py#L216

**Comment by arielsvn** [comment]
Tagging @Miserlou
