### ISSUE TITLE
Use skeleton screens to improve perceived performance in search page

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#363]
![](https://blog.ionicframework.com/wp-content/uploads/2018/03/skeleton.gif)

Some references from @dvenprasad 

- https://blog.ionicframework.com/improved-perceived-performance-with-skeleton-screens/
- https://codeburst.io/achieve-skeleton-loading-with-react-a12404678030
- https://codepen.io/oslego/pen/XdvWmd

**Comment by Miserlou** [comment]
If you're trying to improve performance, the real win would be to start using [prefetch related](https://medium.com/quant-five/speed-up-django-nested-foreign-key-serializers-w-prefetch-related-ae7981719d3f) on API search calls rather than trying to trick the users!

**Comment by arielsvn** [comment]
I'll read about it, definitely we should work on the API first if there're improvements we can do there.

Another reason why Deepa and I started talking about this, was that we added a top loading bar. Which makes the loading animation inside the results look bad.

![2018-10-04 13 53 57](https://user-images.githubusercontent.com/1882507/46492936-fca1e100-c7dc-11e8-8158-80206b0c4322.gif)

**Comment by arielsvn** [comment]
From our discussion, we'll start using [prefetch related](https://medium.com/quant-five/speed-up-django-nested-foreign-key-serializers-w-prefetch-related-ae7981719d3f) on the API (https://github.com/AlexsLemonade/refinebio/issues/711) before moving onto the skeleton screens.

**Comment by arielsvn** [comment]
Optimizations to the API here https://github.com/AlexsLemonade/refinebio/pull/736

**Comment by arielsvn** [comment]
Closing this for now, since we're prioritizing other optimizations first.
