### ISSUE TITLE
Re-visit landing page copy to ensure "harmonized" is communicated correctly

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#367]
Flesh out the copy on landing page to convey it accurately.

Look at 
`
refine.bio is a multi-organism collection of genome-wide transcriptome or gene expression data that has been obtained from publicly available repositories and uniformly processed and normalized. refine.bio allows biologists, clinicians, and machine learning researchers to search for experiments from different source repositories all in one place and build custom data sets for their questions of interest.` for pointers.

**Comment by dvenprasad** [comment]
Changes are **bolded**

Find the data you need
Search **the multi-organism collection of genome wide gene expression data obtained from publicly available sources like GEO, ArrayExpress, and SRA. The data has been processed uniformly and normalized** using a set of standardized pipelines curated by the CCDL.

Create custom datasets
Build and download custom datasets tailored to your needs including gene expression matrices and sample metadata.

**Explore the docs**
**Learn more about our [scientific process](http://docs.refine.bio/en/latest/index.html) or explore [example workflows](http://docs.refine.bio/en/latest/main_text.html#use-cases-for-downstream-analysis) to see how data from refine.bio can help with your analysis.**

@jaclyn-taroni What do you think?

**Comment by jaclyn-taroni** [comment]
I like it! Only one comment -- when you say "scientific process," what do you mean? I immediately think of peer review.

**Comment by dvenprasad** [comment]
By scientific process, I mean our rationale and detailed pipeline information we've described in the docs. What would be the best way to phrase that?

**Comment by jaclyn-taroni** [comment]
Maybe just say "pipelines" ?

**Comment by dvenprasad** [comment]
Mockup

![landing-page](https://user-images.githubusercontent.com/15315514/46691774-aca78d80-cbd3-11e8-9d41-ca22e8903876.png)


Invision: https://projects.invisionapp.com/share/9SNAJ70ME4D/#/screens/300190943_landing-Page
The links area added as notes on the mockup.

The icon for explore the docs is in Assets/explore.svg.

@arielsvn Let me know if you need anything else
