### ISSUE TITLE
Allow users to filter by Platform

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#371]
Add platforms on the filters bar on the search page.

**Comment by dvenprasad** [comment]
![screen shot 2018-10-09 at 4 12 34 pm](https://user-images.githubusercontent.com/15315514/46695653-30ff0e00-cbde-11e8-80f1-1ed1ed6b5db8.png)


We should decide whether or not it needs a search depending on how many platforms are displayed on average for a search.


Invision:
desktop: https://invis.io/EQOHKSKWRM8#/295363740_search_Results-Added

mobile: https://invis.io/9ENIW0SFJ4X#/319579394_search-Results-Filters-Selected

@arielsvn let me know if you need anything else.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/pull/737#issuecomment-429954886 Added `platforms` filters to the search endpoint. But it's returning unformatted values in the names of the platforms.

We should find a way to format these platforms, and maybe drop the fields `pretty_platforms` on the samples and experiments instances.
