### ISSUE TITLE
Add sorting options for search results

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#372]
Allow users to sort by number of samples and time created (experiment date??)

**Comment by dvenprasad** [comment]
Sorting options:
Most No. of Samples
Least No. of Samples
Newest Experiment First
Oldest Experiment First

@jaclyn-taroni  are these sorting options sufficient or are there any other fields we should add? 

On ArrayExpress: there seems to be multiples dates associated: `Submitted on 1 June 2014, last updated on 25 September 2018, released on 5 October 2018`

GEO and SRA just have the `published date`

Which dates do we consider for sorting (for arrayexpress)?

Also, we don't display 'experiment date' anywhere on the search result card or even the experiment. We should add that field at least on the experiment page (both is preferred). 

As far as UI is concerned:
I want to note that the 'Add to Dataset' button has been moved below filter option on mobile version. 

Mockups

Desktop: 
![search_results -sort-options](https://user-images.githubusercontent.com/15315514/46681301-f3d45500-cbb8-11e8-9c4f-a1ee4c2196f7.png)


Mobile:
![search-results-filters-applied](https://user-images.githubusercontent.com/15315514/46681316-fafb6300-cbb8-11e8-9329-6127f7246151.png)


Invision Links:

Desktop: [https://invis.io/RJOHBVCT34Z#/324559647_search_Results_-sort-Options](https://invis.io/RJOHBVCT34Z#/324559647_search_Results_-sort-Options)

Mobile: [https://invis.io/9ENIW0SFJ4X#/319579397_search-Results-Filters](https://invis.io/9ENIW0SFJ4X#/319579397_search-Results-Filters)

**Comment by arielsvn** [comment]
@Miserlou do we have a field in the API to modify how elements are sorted?

**Comment by jaclyn-taroni** [comment]
> On ArrayExpress: there seems to be multiples dates associated: Submitted on 1 June 2014, last updated on 25 September 2018, released on 5 October 2018

@dvenprasad do you know the accession code for that one? I want to take a closer look.

**Comment by dvenprasad** [comment]
@jaclyn-taroni [https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-7219/?query=cancer](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-7219/?query=cancer)

**Comment by jaclyn-taroni** [comment]
I think we want `Submitted on`

**Comment by jaclyn-taroni** [comment]
With respect to experiment date, I'm taking a look at some example experiments on the API

#### GEO
For GEO, we want `submission_date` from the sample annotations. In this example, it's `"Jun 11 2015"`: https://api.refine.bio/samples/?accession_code=GSM1708647

#### SRA

I don't see any source repository date information in the sample annotation for SRA https://api.refine.bio/samples/?accession_code=SRR3098579
Or the corresponding experiment: https://api.refine.bio/experiments/?accession_code=SRP068364

#### Array Express

I also don't see any date information in the sample annotations for ArrayExpress: https://api.refine.bio/samples/?accession_code=E-MTAB-381-hlp-l-1h-3-2
Or the corresponding experiment: https://api.refine.bio/experiments/?accession_code=E-MTAB-381

This info may be somewhere else I'm not looking, but if not, sorting by experiment date doesn't seem feasible.
