### ISSUE TITLE
Create a species compendia page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#375]
Create a page where people can download the species compendia. 
For Electric Eevee,  the page should:

- Mechanism to download the zebrafish compendia
- briefly describe the species compendia
- Link to examples(?)

**Comment by dvenprasad** [comment]
Related to https://github.com/AlexsLemonade/refinebio/issues/508 and https://github.com/AlexsLemonade/refinebio/issues/541

**Comment by jaclyn-taroni** [comment]
@Miserlou asked yesterday if there was a short description of what we do to create species compendia and it looks like that was part of the initial design here: https://github.com/AlexsLemonade/refinebio-frontend/issues/375#issuecomment-438805618

I agree that this should probably be included

cc @dvenprasad @arielsvn
