### ISSUE TITLE
Prevent google from indexing staging.refine.bio

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#376]
![image](https://user-images.githubusercontent.com/1882507/46615280-d4202c80-cae5-11e8-91a6-b449adf22d46.png)

[robots.txt](https://support.google.com/webmasters/answer/6062596?hl=en&ref_topic=6061961)
```
User-agent: *
Disallow: /
```

**Comment by Miserlou** [comment]
Related, we should do all of the Google webmaster tools stuff for all of our domains. @dvenprasad

**Comment by jaclyn-taroni** [comment]
@Miserlou - link domain and analytics (which we have)

**Comment by arielsvn** [comment]
We have `robots.txt` in place

![image](https://user-images.githubusercontent.com/1882507/47227928-fe99a180-d391-11e8-97e9-3fb19ce52af5.png)

And we got refine.bio verified with google search console. Closing this...
