### ISSUE TITLE
Weird Organism Formatting

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#382]
https://www.refine.bio/experiments/649?ref=search

![screen shot 2018-10-10 at 4 38 39 pm](https://user-images.githubusercontent.com/139987/46764641-f7e09f80-ccaa-11e8-9f2d-9dab929e1458.png)

**Comment by arielsvn** [comment]
What should be the correct formatting for these organisms? The original names are:

```
"MUS_MUSCULUS"
"MUS_MUSCULUS_DOMESTICUS"
"MUS_MUSCULUS_MUSCULUS_X_M._M._DOMESTICUS"
```

**Comment by arielsvn** [comment]
Yes, that should be fixed with the next deploy.

![image](https://user-images.githubusercontent.com/1882507/46819127-ece04a80-cd50-11e8-92a6-fd0a2aa005fb.png)
