### ISSUE TITLE
Platform name dropped on Experiment page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#383]
When an experiment is multi-platform, the experiment page only displays one platform.

Search Result:
![screen shot 2018-10-10 at 5 27 05 pm](https://user-images.githubusercontent.com/15315514/46767131-02526780-ccb2-11e8-9ef5-dfdcbe4fc94c.png)

Experiment page:
![screen shot 2018-10-10 at 5 27 11 pm](https://user-images.githubusercontent.com/15315514/46767147-0f6f5680-ccb2-11e8-968b-79757a4f1628.png)

**Comment by arielsvn** [comment]
This should be fixed with the next deploy
