### ISSUE TITLE
Multi-platform Experiments Look a Mess

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#419]
<img width="1233" alt="screen shot 2018-11-07 at 10 07 38 am" src="https://user-images.githubusercontent.com/139987/48151066-3b600680-e275-11e8-9156-c7db7c3aba39.png">

I think we can do a better job of collapsing information there. It also says "Unknown" for Technology, which I don't think is true - it's more like "Multiple", in which case it should +1 to both rather than unknown. That might be an API side issue.

**Comment by arielsvn** [comment]
This is what the API is returning for technology:

![image](https://user-images.githubusercontent.com/1882507/48151274-de714a00-e28e-11e8-8549-f3400c713ea5.png)

What do you mean with "it should +1 to both rather than unknown" ?

**Comment by arielsvn** [comment]
@dvenprasad for experiments with a lot of platforms, what do you think if we put the platforms below?

![image](https://user-images.githubusercontent.com/1882507/48356418-3976b880-e664-11e8-9239-d05d5f0a63d5.png)
