### ISSUE TITLE
Rogue <hr> In Experiment Detail View

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#430]
<img width="1209" alt="screen shot 2018-11-09 at 1 42 08 pm" src="https://user-images.githubusercontent.com/139987/48289716-4fe30100-e425-11e8-975f-99e0324ac2de.png">

**Comment by arielsvn** [comment]
It was originally like that in [the design](https://projects.invisionapp.com/d/main#/console/13557531/325148047/preview).

@dvenprasad what do you think?

**Comment by dvenprasad** [comment]
The <hr> is to separate information not under Submitter Supplied Information. Source repository is experiment level information but doesn't fall under submitter supplied information.

**Comment by arielsvn** [comment]
Closed it by mistake, from waffle

**Comment by dvenprasad** [comment]
Remove the `<hr>` and include it the striped table. 

![Screen Shot 2019-03-19 at 9 15 58 AM](https://user-images.githubusercontent.com/15315514/54608700-a68dc680-4a27-11e9-8611-6637d73c195a.png)
