### ISSUE TITLE
Why Is There No Add All Available Button

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#437]
![screen shot 2018-11-26 at 8 00 42 pm](https://user-images.githubusercontent.com/139987/49051472-04b34700-f1b6-11e8-9f39-699ee3309732.png)

Do I have to go through and all all these page by page

**Comment by arielsvn** [comment]
The *Add all* button is actually at the top of the experiment, next to the title:

![image](https://user-images.githubusercontent.com/1882507/49386456-8f7fce80-f6ed-11e8-8813-a9b7b8bd3c2a.png)

**Comment by arielsvn** [comment]
Why not? IMO at the top we're displaying general information of an experiment, so it makes sense to put the button to add all samples there. At the bottom we show the samples table, where the user can add individual samples or all samples in a page.

Do you have any suggestions on how to improve it?

Tagging @dvenprasad

**Comment by Miserlou** [comment]
Just put the button right there as well. "Scroll away from the thing you are looking at to interact with it" is never going to make any sense.

**Comment by dvenprasad** [comment]
I'm okay with replacing 'Add Page to Dataset' to 'Add to Dataset'.
