### ISSUE TITLE
Modals On Modals

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#444]
![screen shot 2018-11-26 at 8 10 19 pm](https://user-images.githubusercontent.com/139987/49051798-56a89c80-f1b7-11e8-8fa8-5e96a61593ce.png)

Is this intentional? It feels like something has gone wrong if this is happening.

**Comment by arielsvn** [comment]
Yes, it's intentional. I'm gonna try to think of a better way to do this. @dvenprasad any thoughts?

**Comment by dvenprasad** [comment]
Invision:
https://invis.io/XQPVOF0H8DV#/339853681_download-Nested-Modals
