### ISSUE TITLE
Organism Filter Should Be Folded By Default

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#460]
We have far too many Organisms now. Either needs a filter or a fold.

<img width="1792" alt="screen shot 2018-12-08 at 1 07 02 pm" src="https://user-images.githubusercontent.com/139987/49689104-3a2b2f00-faea-11e8-8192-1f66aaef4cad.png">

**Comment by arielsvn** [comment]
Yes, should be solved with https://github.com/AlexsLemonade/refinebio-frontend/issues/446
