### ISSUE TITLE
Download Size Estimates Are Off

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#470]
<img width="1321" alt="screen shot 2018-12-18 at 10 17 49 am" src="https://user-images.githubusercontent.com/139987/50163345-3b104d80-02ae-11e9-98be-9443ec6f03b1.png">

**Comment by jaclyn-taroni** [comment]
Chatting with @arielsvn in person and we think that this can be attributed to the way that we currently smash things for the **gene expression matrix**. Specifically, we're doing an inner join (only retaining genes that are present for every sample) so the number of rows for the same organism can vary quite a bit from dataset to dataset.

Some thoughts on this:

- A design question (tagging @dvenprasad): is it more desirable to get a rough average guess or to overestimate the filesize (or something else entirely)?
- If we want to overestimate, we can find the platform for each organism with the greatest number of Ensembl gene identifiers and use that for our estimates. This is messy in the sense that then you have an organism-specific estimate, though I suppose you could take the average of _that_.
- If we want to take the average approach, we could use @cansav09's work on "what does the missingness landscape look like?" (done during our exploration re: compendium processing) to guide us -- asking "how many genes would a random selection of samples give us?" Currently I think we've only got an idea for human but there was discussion of making those analyses more generalizable.

**Comment by dvenprasad** [comment]
The users look at the file sizes to see how long they will have to wait for the download to finish.  During the evals, users focused more on what files they would be receiving than their sizes. I briefly chatted with @arielsvn and it is possible to get the actual download size when the aggregated files are ready for download. 

So I propose that we remove download sizes from the download summary. We will show the download size on the Dataset Download page instead. Showing it here would be more relevant to the users. 

![screen shot 2019-01-09 at 1 27 32 pm](https://user-images.githubusercontent.com/15315514/50920049-5a644b80-1412-11e9-9a70-86a757bef951.png)
