### ISSUE TITLE
We seem to underestimate download file sizes

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#471]
![image](https://user-images.githubusercontent.com/1882507/50163592-c2f65780-02ae-11e9-901c-316b777b738c.png)

> Jay Scott downloaded 1k meduloblastoma samples last night via refine.bio - big fan of the process. as a short caveat - the file sizes were off. estimate was 18MB - size was > 100MB

**Comment by Miserlou** [comment]
Dupe of https://github.com/AlexsLemonade/refinebio-frontend/issues/470 :)

**Comment by arielsvn** [comment]
missed that one, you beat me by 7 mins. Closing this...
