### ISSUE TITLE
Download Page Continuously Makes Gigantic Requests for Large Datasets

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#472]
I'm not sure why this is. FF.

<img width="1680" alt="screen shot 2018-12-18 at 11 20 25 am" src="https://user-images.githubusercontent.com/139987/50167338-f937d500-02b6-11e9-8bb3-3c8d96428c09.png">

Loading this page for the first time is very slow, which seems very unnecessary as when you View Samples, they don't load instantly (if at all).

**Comment by arielsvn** [comment]
Can you also paste the link to that dataset please?

**Comment by Miserlou** [comment]
https://www.refine.bio/dataset/b5e9e8c3-432f-4b17-8983-86be1dea338d

**Comment by arielsvn** [comment]
While trying to refactor the datasets related API, I found two PR that tried to solve this in different ways:

- https://github.com/AlexsLemonade/refinebio/pull/444 Added a `/dataset/stats/$dataset_id` endpoint, to return additional information for a dataset. We're not using this in the frontend.

- https://github.com/AlexsLemonade/refinebio/pull/517 Adds a new parameter for the dataset endpoint `/?details=true` that also returns the details we need for the downloads page.

Personally I lean towards the second approach, where we could load all the information for the downloads page in a single request by doing `/dataset/$dataset_id/?details=true`, but people might have different opinions.
