### ISSUE TITLE
Missing Space on Filter Counts

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#484]
Is this a regression?

<img width="267" alt="screen shot 2019-01-07 at 2 40 05 pm" src="https://user-images.githubusercontent.com/139987/50789550-979dd180-128a-11e9-8758-b05945c45745.png">

**Comment by arielsvn** [comment]
Good catch! seems that this was introduced with https://github.com/AlexsLemonade/refinebio-frontend/pull/475
