### ISSUE TITLE
Setting up frontend deployment

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#5]
@kurtwheeler and I were talking about how to set up deployment for the frontend and we came up with this list of steps to take:

1. Use a throwaway domain to test the frontend deploy process (@cgreene I believe you mentioned you might have some you're not using?)
2. Host app in S3.
3. Configure CI to deploy automagically to the S3 bucket.
4. Create `api.refine.bio` URL and configuration & exposing the API to the outside world
5. Move `www.refine.bio` landing page to the `refinebio-frontend` repo
6. Make final staging URL point to S3 bucket containing the app

We also have some questions we could use some help answering:

1. What URL should staging live at? `refine.bio/staging`??
2. Where should staging point to for the backend?
    * production API? staging API? local machine?

Any feedback you guys could give would be helpful, thanks!

**Comment by cgreene** [comment]
I have http://placebotol.com - happy to use it for this. Seems good to use it for something 😄

**Comment by dongbohu** [comment]
Since the front end of refine.bio is separate from the backend, it think it is okay to let the front end staging point to the production API.

**Comment by kurtwheeler** [comment]
@cgreene: For this staging server, how careful do we need to be about hiding these URLs. Would `staging.refine.bio` and `api.staging.refine.bio` be too easy to stumble across. Do we want to deploy these to `http://placebotol.com` and `http://api.placebotol.com/` for now?

**Comment by cgreene** [comment]
I think `staging.refine.bio` and `api.staging.refine.bio` would be fine

**Comment by cgreene** [comment]
@kurtwheeler reports this is closed
