### ISSUE TITLE
Make Email Address an Auto-Populatable Field

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#507]
I'm not sure what this takes, I see some websites to do it, but I'm tired of manually typing in my email every time.

**Comment by Miserlou** [comment]
This might be FF only

**Comment by arielsvn** [comment]
I think I have seen it on my iphone as well. Do you have any link to a website that does it?

**Comment by arielsvn** [comment]
@dvenprasad suggested we hide the checkbox to signup for the newsletter for subscribed users.
