### ISSUE TITLE
[Discussion] Don't Sort By Samples If Search Query Is an Accession

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#519]
I think recent changes to sorting (or perhaps indexing) changed how results in the accession format are returned, ex: https://www.refine.bio/results?q=GSE24528 - I'd expect that accession to be at the top because it's a better match, although it has less samples. So, not really sure what we want to do about this.

**Comment by arielsvn** [comment]
Is there a way to sort the results by "Relevance"? We could add that option and make it the default

**Comment by dvenprasad** [comment]
If a user is searching by accession, they would expect just one result - the experiment with the accession. 
What's the basis for the other experiments to show up in the search results?

**Comment by Miserlou** [comment]
I think you'd expect that first, but if there are other experiments which mention your accession in their body text, you'd probably want to see those if they're available so you can see what other people have already done with that sample set.

I haven't used it yet, but ES has a notion of "boosting", we could try boosting the accession_code field. I don't know what that'll do but I assume it'll bias matching towards that field over body fields.

**Comment by Miserlou** [comment]
Or you can only search a specific field if it's in accession format already, ex:

https://api.refine.bio/es/?search=accession_code:GSE24528

**Comment by arielsvn** [comment]
Assuming that users will be interested in both

- Searching experiments that mention an accession code in their body text
- Searching by accession code, which should return a single result.

We could show a suggestion to the user to switch between these modes: 

![image](https://user-images.githubusercontent.com/1882507/52722654-0ea94280-2f7a-11e9-8b5d-c5ddde9b40fd.png)

**Comment by dvenprasad** [comment]
When users are searching by accession, they are usually looking for that specific experiment. Showing them the experiment with the accession code should be prioritized over showing them other results. 
 
I agree with @Miserlou's comment above: https://github.com/AlexsLemonade/refinebio-frontend/issues/519#issuecomment-461066972

Something like this:
![img_20190214_110317 1](https://user-images.githubusercontent.com/15315514/52800088-1257ca80-3049-11e9-8230-e526d8a1d5b4.jpg)


If we're okay with this solution, I'll mock it up.

**Comment by arielsvn** [comment]
If someone uses the API directly and searches for an accession code (`search=GSE4040`), what should be the expected result?

I like this solution, it would solve the issue for the users of the web app but my concern is the people that use the API directly.

**Comment by dvenprasad** [comment]
Mockup:
![search_results-accession](https://user-images.githubusercontent.com/15315514/52972373-b367bd80-3388-11e9-997d-c0466bdfdf51.png)


Invision:
https://invis.io/J8QKMRVWY3F#/347464324_search_Results-Accession

@arielsvn let me know if you need anything else.

**Comment by arielsvn** [comment]
Do we have any rules to identify what is an accession code? Initially I was tempted to use a regular expression matching:

```
{GSE | ERP | SRP} + {4 to 6 digits}
```

But then got confused after I saw other accession codes like: `E-MTAB-3731`, `E-TABM-878`, `E-MEXP-3497`
