### ISSUE TITLE
No robots.txt

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#520]
We get a lot of crawlers but provide them no instruction.

**Comment by arielsvn** [comment]
For some reason it's not working on production, but staging seems to have it. https://staging.refine.bio/robots.txt

Will look into the S3 configuration to see if there's something missing.

**Comment by arielsvn** [comment]
Actually, that was intentional, we disabled all crawlers for staging.refine.bio with https://github.com/AlexsLemonade/refinebio-frontend/issues/376

I assumed we wanted bots to crawl refine.bio. Do you think we should limit any specific paths?
