### ISSUE TITLE
Experiment Title Is H3, Not H1 // Basic Page Hierarchy Hygeine

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#524]
![screen shot 2019-02-09 at 7 25 13 pm](https://user-images.githubusercontent.com/139987/52527988-8d635e80-2ca0-11e9-913f-3401e7337e20.png)

I was hoping that we'd be a top result for a given experiment query, ex "DNA methylation and gene expression profiling of primary medulloblastoma samples" - and in fact, we are on the first page, but the only the search is linked. This is a result of us not practicing basic SEO/page hierarchy heigene, so crawlers don't know what things are titled or where they are canonically located.

**Comment by Miserlou** [comment]
Related: https://github.com/AlexsLemonade/refinebio-frontend/issues/510

**Comment by arielsvn** [comment]
Saw us on the 3rd place for an accession code search

![image](https://user-images.githubusercontent.com/1882507/52885533-92f8f280-313f-11e9-9c63-65f9e9d9600f.png)
