### ISSUE TITLE
Technology Filter Wonky

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#525]
![screen shot 2019-02-11 at 10 37 53 am](https://user-images.githubusercontent.com/139987/52573948-36b56c00-2de9-11e9-9187-a46dc78ee4fa.png)

I bet this is API driven but probably just needs some frontend finessing

**Comment by arielsvn** [comment]
Yes, all those values are being returned by the API. Strange that **Rna-Seq** is displayed separately, I thought we had addressed that.

**Comment by arielsvn** [comment]
Fixed with latest deploy

![image](https://user-images.githubusercontent.com/1882507/54536561-50594e80-4967-11e9-9e17-95e0f476a160.png)
