### ISSUE TITLE
Optimize samples table in experiments page

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#529]
@dvenprasad as part of our discussion about https://github.com/AlexsLemonade/refinebio-frontend/issues/495 we discussed the possibility of doing the same in the experiments page. Maybe with a toggle button.

![image](https://user-images.githubusercontent.com/1882507/52661370-e533dc80-2ecf-11e9-981b-b70b658f76f1.png)

Where do you think we should put it?

**Comment by dvenprasad** [comment]
Mockup:
![screen_shot_2019-02-13_at_3_02_33_pm](https://user-images.githubusercontent.com/15315514/52740289-b6396b80-2fa0-11e9-983f-0fe91f96f49d.png)


![screen_shot_2019-02-13_at_3_02_47_pm](https://user-images.githubusercontent.com/15315514/52740294-bafe1f80-2fa0-11e9-9f67-e996a37ca09c.png)


Invision:
https://invis.io/KXQI2LZPDVW#/346459354_experiment-Page

https://invis.io/K2QI2M8Q7JW#/346686224_experiment-Page-Expanded-Table

Expand and Collapse icons are in Assets/Icons folder. 

@arielsvn let me know if you need anything else
