### ISSUE TITLE
Drop haiku usages

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#533]
We currently use [haiku](https://www.haiku.ai/) for two animations: the [spinner](https://share.haiku.ai/b2988acf-eb94-4455-b638-637da4a25d86/latest) and the processing dataset animation.

@dvenprasad is it possible to save these animations as gifs? It would be nice to remove the dependency to Haiku as it takes about 30% of our bundle size.

![image](https://user-images.githubusercontent.com/1882507/52742789-8a20e900-2fa6-11e9-9dd1-9bb6a4ce6020.png)

**Comment by dvenprasad** [comment]
![animation 1](https://user-images.githubusercontent.com/15315514/52744802-a1aea080-2fab-11e9-881a-4b85fd3affea.gif)
![animation 2](https://user-images.githubusercontent.com/15315514/52744803-a2473700-2fab-11e9-8ecf-619e05474da9.gif)


I'm not too confident about the quality
