### ISSUE TITLE
Homo Sapien[s]

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#535]
I don't know how this s is getting cut off:

![screen shot 2019-02-14 at 11 47 14 am](https://user-images.githubusercontent.com/139987/52802604-4aadd780-304e-11e9-95b4-515b449304a8.png)

**Comment by arielsvn** [comment]
maybe related to https://github.com/AlexsLemonade/refinebio-frontend/issues/525

**Comment by kurtwheeler** [comment]
I know I said I thought I knew what caused this but it's not that so I have no idea.

**Comment by arielsvn** [comment]
Seems to be working now! 🔥 

![image](https://user-images.githubusercontent.com/1882507/54767607-e2658f00-4bd3-11e9-8e4f-c086533a20c3.png)

**Comment by Miserlou** [comment]
oh thank god

**Comment by Miserlou** [comment]
For anybody who ends up googling similar weirdness, the "snowball" filter that DRF-ES-DSL recommends as a default will turn some plural English words into their singular forms, which is why this was happening for 'Sapiens' but not 'Musculus'. Slightly maddening to debug.
