### ISSUE TITLE
Cannot view any of the experiments without downloadable samples

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#538]
We will need to display them, if we want to track requests for datasets to be processed (https://github.com/AlexsLemonade/refinebio/issues/1056) 

![screencapture-refine-bio-results-2019-02-18-12_18_06](https://user-images.githubusercontent.com/15315514/52967233-692a1080-3377-11e9-8d18-bfb9228e7b7e.png)

**Comment by arielsvn** [comment]
Now that sorting was fixed, these experiments can be found in the [last page](https://www.refine.bio/search?p=3608)

![image](https://user-images.githubusercontent.com/1882507/52975819-f465cf00-3394-11e9-9632-af233f19efc8.png)
