### ISSUE TITLE
Application Size Is Over 1MB

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#543]
![screen shot 2019-02-21 at 10 29 48 am](https://user-images.githubusercontent.com/139987/53180515-b3073680-35c3-11e9-9ed9-f476005cf8b0.png)

Maybe I'm being an Old Person^tm, but this seems incredibly large for a simple web application. Why is this so large? Is it not minified? It does use the cached version on the next load, so that's good.

Furthermore, it looks like the size and the transfered sized are the same, meaning that we're not using `gzip` (or similar) for our frontend assets. 

It also looks like we're not loading our external scripts async since hotjar blocked the page render for me, but that's probably a different ticket.

**Comment by arielsvn** [comment]
This might be a good opportunity to also add some of the recommendations from [google's pagespeed insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.refine.bio%2Fsearch).
