### ISSUE TITLE
More Filter Wackiness

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#569]
![2019-03-18 16 01 38](https://user-images.githubusercontent.com/139987/54559793-3df70900-4997-11e9-8012-1941987ef0b1.gif)

a) Shouldn't selecting the largest platform return results?
b) This hilarious scrolling bug prevents us from going to the footer in this case

**Comment by arielsvn** [comment]
wow that's strange! Seems that there're several things going wrong at once there

**Comment by arielsvn** [comment]
> a) Shouldn't selecting the largest platform return results?

This seems to be an API issue, the platform filter doesn't work for all platforms. Created an issue in the backend with more details https://github.com/AlexsLemonade/refinebio/issues/1181

> b) This hilarious scrolling bug prevents us from going to the footer in this case

Should be fixed with #583
