### ISSUE TITLE
Add 'Next Steps' to Processing dataset/download dataset page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#597]
Uncovered during testing. It may be time to add 'Next Steps' which was initially proposed and removed as we did not have content for that yet. 

![Screen Shot 2019-04-07 at 2 40 38 PM](https://user-images.githubusercontent.com/15315514/55688125-32b64e00-5943-11e9-80c8-0a96d4c542e1.png)

Potential Links: 
- Link to README file people receive when they download. (Only one person/ 6 actually opened and read the README file)
- Link to example notebooks. 
- Link to processing methods in docs

**Comment by dvenprasad** [comment]
Proposed 'Next steps' links:
- Get started with your dataset (Link to page providing the same info as [README](https://github.com/AlexsLemonade/refinebio/blob/dev/workers/README_DATASET.md))

- Convert ENSEMBL IDs to Gene Symbols (Link to this [notebook](https://github.com/AlexsLemonade/refinebio-examples/blob/master/ensembl-id-convert/ensembl_id_convert.nb.html))

- Follow an example differential expression analysis ( Link to this [notebook](https://github.com/AlexsLemonade/refinebio-examples/blob/master/differential-expression/gene_DE.Rmd))

- Learn more about how we source and process data (Link to docs) 

@jaclyn-taroni Are these examples at an appropriate level to help people get started? 

Also, should we link them to the notebooks directly? or the directory on Github? For the differential expression example, there's also an example using GenePattern Notebooks.

**Comment by jaclyn-taroni** [comment]
LGTM. I would link to the module for any of the examples so folks would land at the README for a particular example.

**Comment by dvenprasad** [comment]
Show `Next Steps` only on the following states of the Download Dataset page
- Processing
- Ready for Download

Next Step links:
[Get started with your dataset](http://docs.refine.bio/en/latest/getting_started.html#getting-started-with-a-refine-bio-dataset)

[Convert ENSEMBL IDs to Gene Symbols](https://github.com/AlexsLemonade/refinebio-examples/tree/master/ensembl-id-convert) 

[Follow an example differential expression analysis](https://github.com/AlexsLemonade/refinebio-examples/tree/master/differential-expression)

[Learn more about how we source and process data](http://docs.refine.bio/en/latest/index.html)

Mockup:
![download-dataset-download-ready-clicked](https://user-images.githubusercontent.com/15315514/56236585-fcba4d80-6057-11e9-9cf2-0dd302ef1cdb.png)


Invision Links:

https://invis.io/JYKO59G89SP#/302048787_download-Dataset-Download-Ready
https://invis.io/VDRKUHOA6WN#/302071994_download-Dataset-Download-Ready-Clicked
https://invis.io/2SKO5BXAH3X#/292620200_download-Dataset-Processing
https://invis.io/3KRKUR6JHA6#/304099502_download-Dataset-Download-Ready-Tc

Illustration is in Assets/images/download-workflow/tubey-adventure
