### ISSUE TITLE
Add highlights to Filters on Samples Table

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#598]
When user searches term 'male', samples with 'female' also show up

![Screen Shot 2019-04-07 at 2 46 22 PM](https://user-images.githubusercontent.com/15315514/55688203-11099680-5944-11e9-980a-83a9e5151dc9.png)

Easy fix would be to add highlights to the filter term like we do on the search page.

Could we also rank exact matches higher than partial matches?

**Comment by arielsvn** [comment]
> Could we also rank exact matches higher than partial matches?

To my knowledge there's no way of doing this with Postgres, we would have to add something like elastic search to be able to sort these results.

**Comment by kurtwheeler** [comment]
Is there a reason to not use elastic search to sort results like this? The highlighting solution in #624 would help with this issue, but users could end up having to scroll over lots of non-relevant results to find the ones they're searching for.

**Comment by arielsvn** [comment]
> Is there a reason to not use elastic search to sort results like this?

Not really, using elasticsearch would be ideal, and it would also allow us to filter samples per column which is something we'll want to add in the future. #624 was an easy fix.

**Comment by kurtwheeler** [comment]
Perfect then! Is there an issue around using ES or will that be part of this one as well?

**Comment by arielsvn** [comment]
I think that should be a different issue, will create one for it in the backend.
