### ISSUE TITLE
"No Downloadable Samples" experiments are added with "Add Page to Dataset"

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-frontend#599]
### Problem: 
If I click "Add Page to Dataset" on a page that includes an experiment with 0 downloadable samples, those 0 sample experiments will be added to the Experiments view even though there are no samples. 

Here this screen shot shows the 3rd, 4th, and 5th experiments added don't have any samples.

![Screen Shot 2019-04-09 at 1 17 35 PM](https://user-images.githubusercontent.com/23458084/55820858-1d1f6080-5aca-11e9-955d-036fd9e197f9.png)

Side note, this does not happen to a page with all experiments having no samples, because the button appears to be disabled on those pages.

**Comment by cansav09** [comment]
Although for species aggregated data this isn't an issue, if a user tries to download this data by experiment: The experiments with `No Downloadable Samples` end up getting folders and metadata files. The metadata files are essentially empty except that they still have column names.

**Comment by arielsvn** [comment]
This will be fixed with #612
