### ISSUE TITLE
Experiment count by species on download page is incorrect

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-frontend#601]
See below when I loaded some datasets into the shopping cart: 

![Screen Shot 2019-04-12 at 10 05 45 AM](https://user-images.githubusercontent.com/23458084/56044185-9e663580-5d0c-11e9-9966-047196bae731.png)

Though it has happened at least twice, this doesn't appear to be a consistent problem. I have been trying to replicate it based on the circumstances that lead me to this in the first place, but now it isn't happening again. This occurred after I clicked "Start Processing" and I am not certain if it happened before that. I will look out for this glitch and see if I can provide more information. But perhaps it's something that is more evident in the code.

**Comment by cansav09** [comment]
I believe I've determined this only happens after you click download and after the dataset has started processing.

**Comment by arielsvn** [comment]
@cansav09 Can you check if you can reproduce this one again? It seems to work now that https://github.com/AlexsLemonade/refinebio/pull/1272 was deployed

**Comment by cansav09** [comment]
Tried to duplicate it, and where it usually glitches it did not this time! Looks like it's fixed to me!

**Comment by arielsvn** [comment]
Great, thanks! I'm gonna close this, feel free to reopen if you see the problem again!
