### ISSUE TITLE
Platforms come up multiple times due to spacing differences

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-frontend#602]
Here's examples of what I mean. Here all the samples are IlluminaHiSeq2000, but one has space and one does not so the platform info doesn't technically match and the info is repeated: 

<img width="1132" alt="Screen Shot 2019-04-15 at 3 04 21 PM" src="https://user-images.githubusercontent.com/23458084/56158443-05475100-5f90-11e9-9ad7-4357f4963ca8.png">

Another example: 
<img width="1149" alt="Screen Shot 2019-04-15 at 3 06 10 PM" src="https://user-images.githubusercontent.com/23458084/56158530-450e3880-5f90-11e9-947f-38ea75923bf9.png">

This appears to only be an issue on the dataset page itself and NOT on the search page entries.

**Comment by arielsvn** [comment]
@kurtwheeler do you think running the migrations in https://github.com/AlexsLemonade/refinebio/pull/783 will solve this?

**Comment by kurtwheeler** [comment]
This issue is caused by the backend and there'a an issue there to track it: https://github.com/AlexsLemonade/refinebio/issues/1249
