### ISSUE TITLE
Enable searching with a list of accession codes

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#603]
Based on use cases in https://github.com/AlexsLemonade/refinebio/issues/97, we should enable users to search with a list of accession codes.

**Comment by arielsvn** [comment]
Should we allow a list of comma separated accession codes? or were you thinking of another format @dvenprasad ?

![image](https://user-images.githubusercontent.com/1882507/56692095-6c12eb80-66af-11e9-9a9b-1403501c265a.png)

**Comment by dvenprasad** [comment]
Yep comma separated list of accessions. The screenshot looks like the result I would expect.

**Comment by arielsvn** [comment]
Api query for multiple accession codes: https://api.refine.bio/es/?search=accession_code:GSE11611&search=accession_code:SRP068957
