### ISSUE TITLE
Close the download loop for Species Compendia

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#605]
Design for what happens after someone downloads a Species Compendia.

Guide them to examples and documentation.

**Comment by dvenprasad** [comment]
Next steps:
- [Get started with the species compendia] (http://docs.refine.bio/en/latest/getting_started.html#getting-started-with-species-compendia)
- [Check out the quality check report for the danio rerio compendia](https://github.com/AlexsLemonade/compendium-processing/tree/master/quality_check)
- [Learn how the species compendia is created](http://docs.refine.bio/en/latest/main_text.html#species-compendia)

@jaclyn-taroni do these seem reasonable? Also, is the phrasing okay for the QC link (second one)?

**Comment by jaclyn-taroni** [comment]
The first and third points seem reasonable. I think the second point should mirror what we have in the README / getting started section for the species compendia

> See our exploratory analyses in test species compendia

Would also reorder to: 1, 3, 2

**Comment by dvenprasad** [comment]
Updated Next Steps copy/order:
- [Get started with the species compendia](http://docs.refine.bio/en/latest/getting_started.html#getting-started-with-species-compendia)
- [Learn how the species compendia is created](http://docs.refine.bio/en/latest/main_text.html#species-compendia)
- [See our exploratory analyses in test species compendia](https://github.com/AlexsLemonade/compendium-processing/tree/master/quality_check)

Mockup:

![species-compendia-downloading](https://user-images.githubusercontent.com/15315514/56313198-014a3900-6120-11e9-8876-72ec7754a47f.png)


Invision:

https://invis.io/ECRLOP995FY#/358706636_species-Compendia-Downloading
