### ISSUE TITLE
Request for experiment redirects to Landing Page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#607]
When user views all results and navigates to the last page and then clicks on the request experiments card, the front-end navigates back to the landing page.

**Comment by arielsvn** [comment]
Does this still happens to you? I wasn't able to reproduce it.

**Comment by dvenprasad** [comment]
Yep. I think @cansav09 also had the same issue.

**Comment by cansav09** [comment]
Yes, to reproduce it, I keep the search bar blank and go to the very last page, then click the `Didn't see a related experiment? Let us know` button.

**Comment by arielsvn** [comment]
closed with #626
