### ISSUE TITLE
Add "loading" state for buttons

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#613]
Sometimes adding samples to dataset takes a while, especially when the number of samples is large. Currently "loading" is indicated by the progress bar on the top but it does not make it clear to users that refine.bio is working on adding those samples to their datasets. 

Adding a loading state to the button makes it clear and makes the system feel more "responsive" to users.

@arielsvn  Reference for loading state: https://coreui.io/docs/components/loading-buttons/

**Comment by wvauclain** [comment]
Closed by #688
