### ISSUE TITLE
Restructure Landing Page to elaborate what users can do with refine.bio data

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#616]
We should keep this as it describes what users can do on refine.bio. We need add information on what people can do with refine.bio's output. 
![Screen Shot 2019-04-23 at 3 06 09 PM](https://user-images.githubusercontent.com/15315514/56608816-a447fa80-65d9-11e9-866b-5b1caf8c00a5.png)

Additional Copy:
You can use [refine.bio](http://refine.bio) datasets for preliminary assessment of biological signals and to accelerate validation of your research findings. 

**Differential Expression**
Learn how you can use [refine.bio](http://refine.bio) to do differential expression analysis with refine.bio datasets.
<link to example>

**Normalize your own data** 
Learn to normalize your data using [refine.bio](http://refine.bio)'s reference distribution to compare your own data with refine.bio datasets. 
<link to example>

**Species Compendia**
Our Species compendia offers datasets which has been processed and aggregated by species built for machine learning applications
<link to Species Compendia page>

 **Explore the docs**
Learn more about how we source and process our data.
<link to docs>

---
@jaclyn-taroni could you please take a look if this make scientific sense? 
I chose the examples based on popularity and also to show flexibility of use of refine.bio's data. If there are other examples which are better suited for this purpose, I'm happy to swap them in.

**Comment by jaclyn-taroni** [comment]
I would swap in **Pathway analysis** for **Normalize your own data**. 
> Learn how you can use [refine.bio](http://refine.bio/) data to identify pathways that are active in your biological condition of interest.

Note that there are outstanding PRs for this module and at least one more incoming https://github.com/AlexsLemonade/refinebio-examples/pull/53, https://github.com/AlexsLemonade/refinebio-examples/pull/55, https://github.com/AlexsLemonade/refinebio-examples/pull/56.

**Comment by jaclyn-taroni** [comment]
An additional blurb (reworking of "Normalize your own data"): 

> **Use your data alongside refine.bio data**
> We make our [transcriptome indices](http://docs.refine.bio/en/latest/main_text.html#transcriptome-index) and [our reference distributions used for quantile normalization](http://docs.refine.bio/en/latest/main_text.html#quantile-normalizing-your-own-data-with-refine-bio-reference-distribution) available to make your own data more comparable to refine.bio data.

**Comment by dvenprasad** [comment]
Mockup:

![landing-page](https://user-images.githubusercontent.com/15315514/56818055-d85b2f80-6814-11e9-8a4b-ab062bbc6d39.png)

Invision:
https://invis.io/8TJTF8K34AX#/300190943_landing-Page

Assets are in landing-page-assets

@arielsvn I have left notes on the invision mockup. There are other small changes which I have noted along with the links. Let me know if there's anything else you need.

**Comment by arielsvn** [comment]
Those look great, thanks @dvenprasad. It might be useful to also update the mobile mockups for the landing page.

**Comment by dvenprasad** [comment]
Invision mobile mockup: https://invis.io/9ENIW0SFJ4X#/360320419_mobile-Landing-Page
