### ISSUE TITLE
Is it possible to stylize the hotjar popup?

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-frontend#625]
When it pops up it seems a bit jarring to me because it doesn't seem to match the rest of the page:

![image](https://user-images.githubusercontent.com/4026833/56767948-fb390580-677a-11e9-9363-42c34ee24167.png)

This is definitely just stylistic so it should be low priority, and if it's not possible it's not that big of a deal.

**Comment by dvenprasad** [comment]
I can sorta customize it to the extent that I can give it different "skin" color.

**Comment by dvenprasad** [comment]
@kurtwheeler 
![Screen Shot 2019-04-26 at 10 20 42 AM](https://user-images.githubusercontent.com/15315514/56814345-fde43b00-680c-11e9-9742-7fb10c84fb5a.png)

This any better? This is probably the extent to which I can make changes

**Comment by kurtwheeler** [comment]
It does look better to me I think.
