### ISSUE TITLE
"Regenerate Files" button broken

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-frontend#633]
### Problem
Here's a dataset that I made a week ago (on 5/2/2019): 
https://www.refine.bio/dataset/72ba0469-0fa4-418f-9973-7203d840d44c

When I try to use the "Regenerate Files" button nothing happens. @kurtwheeler says it's a Javascript error. I don't have anymore information or context around this problem.

**Comment by arielsvn** [comment]
this is working now.

**Comment by jaclyn-taroni** [comment]
@arielsvn @kurtwheeler there was some discussion last week about ensuring backwards compatibility (not sure that that's the exact right term here) -- has this been satisfied as well?

**Comment by arielsvn** [comment]
Can you explain a bit more? When a dataset needs to be re-generated, behind the scenes we create a new one in the backend and add the same samples that were in the old one.

**Comment by jaclyn-taroni** [comment]
If we make changes to a processor or the smasher between the time that a dataset is _initially_ generated and when it's regenerated via this button, what happens?

**Comment by arielsvn** [comment]
The new dataset would be generated using the latest changes to the processor/smasher, the starting point (dataset options, samples) is what it would be the same as the old one. Is this what we want here?

**Comment by jaclyn-taroni** [comment]
Chatted with @kurtwheeler -- essentially we need to make it such that no smasher options are removed and if they are depreciated we need to make sure to handle them. This is outside of the scope of the ticket but thought it was worth documenting here.
