### ISSUE TITLE
Search doesn't always default to best match results

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#638]
Got this comment via hotjar
>I was trying to update my search from within the search results window.
I started by querying "neural stem cells", then added "embryonic" inside the results menu. When I updated the search, the results were no longer relevant to NSCs or embryonic.

The results are there but when the user modifies/starts a new search from the results page, the new results defaults to `Most number of samples` instead of `Best Match`

I tried it with different terms and it still defaulted to `Most number of samples`.

**Comment by arielsvn** [comment]
fixed by #644
