### ISSUE TITLE
Add option to filter "no downloadable samples" out

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-frontend#639]
I was searching for a small experiment to use for testing so I ordered by "least No. of samples" and all I see is pages of experiments with no downloadable samples. I think we should provide an option to filter all results like that out. I also think it makes sense outside of this context because unless you're looking for specific experiments and want to see that they're there but don't have downloadable samples, you probably wanna filter all the experiments you can't add to your dataset anyway.

**Comment by cgreene** [comment]
The ticket might be to default to not showing those, but to have something like a text link that says:
"Some items in your search results had now downloadable samples, click here to display them?"

**Comment by arielsvn** [comment]
@dvenprasad where do you think we should show this option?

**Comment by dvenprasad** [comment]
@cansav09 brought up the idea of filtering by number of downloadable samples. Perhaps we can combine both.

I like the idea of not showing it by default. It could be a filter instead which says `Show results with 0 downloadable samples`

**Comment by arielsvn** [comment]
@dvenprasad would you mind updating the design with this filter?

**Comment by dvenprasad** [comment]
Here are the updated designs. I've marked what is changed. 

**The copy is `Hide non-downloadable experiments`**

Desktop:
![search_results-annotated](https://user-images.githubusercontent.com/15315514/61226183-f63b8080-a6ef-11e9-80fa-357944ffcdf2.jpg)

Mobile:
![search-results-filters-applied](https://user-images.githubusercontent.com/15315514/61226207-ffc4e880-a6ef-11e9-8c82-5a17cf0e2d21.jpg)

Invision:

https://invis.io/9SNAJ70ME4D#/347464324_search_Results-Accession
https://invis.io/9ENIW0SFJ4X#/319579396_search-Results-Filters-Applied

@arielsvn let me know if you need anything else.
