### ISSUE TITLE
Hide Sentry key

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#641]
@kurtwheeler noticed that we're exposing our sentry key in the code. We should hide it.

**Comment by cgreene** [comment]
My impression is that this is not considered to be a problem for public keys, as the key is considered essentially public (this also aligns with https://github.com/getsentry/sentry/issues/5940 ). I think we should be already set up with the public part only. Are we doing something different?

**Comment by arielsvn** [comment]
Yes we're using the public key, problem is that since it's part of the source code any production build of the repository will also report errors to sentry. We thought about removing it from the code and having the key as an environment variable.
