### ISSUE TITLE
Add link to github somewhere

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#659]
At least for me, when visiting www.refine.bio it's not obvious that all source code is available on github. @dvenprasad what do you think if we add a link somewhere to https://github.com/AlexsLemonade?

**Comment by dvenprasad** [comment]
We have it on the footer. We could also add the github ribbons on the header. https://github.blog/2008-12-19-github-ribbons/

Although we should replace the phrasing. Not a huge fan of `Fork me on Github`

**Comment by dvenprasad** [comment]
We can use this: https://github.com/tholman/github-corners

**Comment by arielsvn** [comment]
Oh I had missed the icon in the footer.

I don't like the `Fork me on Github` either. The corner seem like a better idea, we can show it only on large screens. What color should we use? black?

**Comment by dvenprasad** [comment]
Black on white headers and white on the gradient headers?

**Comment by cgreene** [comment]
Will it serve the dual purpose of being both apparent to those who are looking for the code while being unobtrusive to those who would be confused by it?

**Comment by arielsvn** [comment]
I think it shouldn't be a problem if we only show it on large screens

![image](https://user-images.githubusercontent.com/1882507/59207595-52e9cf80-8b75-11e9-8f4b-c123164beba9.png)

**Comment by arielsvn** [comment]
> Black on white headers and white on the gradient headers?

@dvenprasad I couldn't find an easy way to get that effect, this is the closest I got:

![2019-06-14 14 44 40](https://user-images.githubusercontent.com/1882507/59531092-0d9a0a80-8eb3-11e9-8464-d8f6c3e23e87.gif)

Something like that works? Do you have any other ideas of how to make it work?
