### ISSUE TITLE
Sample Shows Up As Not Processed

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio-frontend#673]
I was looking through old backend issues and I found this experiment: https://www.refine.bio/experiments/GSE9338/expression-data-from-mus-musculus-subspecies-and-their-f1-hybrids-for-3-tissues-brain-liver-testis. In the screenshot, it says that it can be added to the database, but when looking at the frontend now, it does not show up as processed.

@kurtwheeler looked at the server and it is processed, and the API says that it is processed, but the frontend does not display it as processed.

API output:

```json

    "samples": [
        {
            "accession_code": "GSM237772",
            "platform_name": "[Mouse430_2] Affymetrix Mouse Genome 430 2.0 Array",
            "pretty_platform": "Affymetrix Mouse Genome 430 2.0 Array (mouse4302)",
            "technology": "MICROARRAY",
            "is_processed": true
        },
        {
            "accession_code": "GSM237755",
            "platform_name": "[Mouse430_2] Affymetrix Mouse Genome 430 2.0 Array",
            "pretty_platform": "Affymetrix Mouse Genome 430 2.0 Array (mouse4302)",
            "technology": "MICROARRAY",
            "is_processed": true
        },
        etc.
    ],
```

**Comment by arielsvn** [comment]
This is related to https://github.com/AlexsLemonade/refinebio/issues/1162 and should be fixed once https://github.com/AlexsLemonade/refinebio/pull/1341 and https://github.com/AlexsLemonade/refinebio-frontend/pull/660 are deployed.

In this case, the samples are processed but we don't have QN targets for them. The organisms with qn targets associated can be viewed at https://api.refine.bio/qn_targets_available

Thanks for filing this, keep them coming! 👋

**Comment by arielsvn** [comment]
This should be fixed now 
![image](https://user-images.githubusercontent.com/1882507/60460475-de54fe80-9c11-11e9-8559-52ff5cb4f780.png)

Feel free to reopen if you see the issue again.
