### ISSUE TITLE
Use computed_files endpoint instead of deprecated compendia endpoint

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#683]
The [/compendia](https://api.refine.bio/#tag/compendia) endpoint will be removed in future releases of the API, since the same result can be obtained using [/computed_files](https://api.refine.bio/#tag/computed_files).

https://api.refine.bio/computed_files/?is_compendia=True&is_public=True

**Comment by arielsvn** [comment]
@kurtwheeler what do you think of this? @wvauclain suggested that we should keep both endpoints and I was almost convinced of this, but I saw we don't have plans to have the python package query `/compendia`. The only use case for it is in the frontend?

When I filed this it was thinking of making the API simpler by reducing the number of endpoints.

**Comment by cgreene** [comment]
Big fan of simpler! Fewer endpoints! Less duplication! :-D

**Comment by arielsvn** [comment]
We added `CompendiumResult` and decided to keep the `/compendia` endpoint to serve those models.
