### ISSUE TITLE
Loading icon is low resolution

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio-frontend#701]
When the browser zoom level is set higher than 100%, the loading icon is noticeably fuzzier than the rest of the website. I think this is a fairly common setting on laptops with 1080p or 4k displays to make websites more readable.

![image](https://user-images.githubusercontent.com/13942258/61461750-55db9b00-a93f-11e9-92a2-b8980549e883.png)

**Comment by arielsvn** [comment]
@dvenprasad is it possible to generate it with a higher resolution? I think we tried that that was the highest we could get, but I might be wrong.

**Comment by dvenprasad** [comment]
So the tool that I used to generate this changed their business model and I no longer have access to edit it. 

I know there are some AfterEffects alternatives (which are way better than this) and I'll regenerate it.

**Comment by wvauclain** [comment]
Closed by #703
