### ISSUE TITLE
Do people search on google for sample accession codes?

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#702]
Seems that there aren't many results on google for sample accession codes.

![image](https://user-images.githubusercontent.com/1882507/61485700-ce5a5000-a96f-11e9-8446-13da5266c79b.png)

I'm sure we can appear there if we had a dedicated sample page and maybe get more traffic to refine.bio

@jaclyn-taroni @dvenprasad do people search for sample accession codes or was that just me?

**Comment by cgreene** [comment]
I sometimes search for sample accession codes. More often experiment, but occasionally sample.

**Comment by dvenprasad** [comment]
I think not. maybe very rarely.... I haven't had anyone talk about searching with sample accessions.

**Comment by jaclyn-taroni** [comment]
I usually search experiment accession codes, but have used sample accession codes rarely.

**Comment by arielsvn** [comment]
I think it might be worth to add a dedicated samples page, even if it's not too sophisticated. I don't think there's a way to know the total volume of searches of sample accession codes, but if each one of the 1MM samples we plan to have gets searched once every 50 years (is this too optimistic?). That means ~50 queries per day.

**Comment by wvauclain** [comment]
I think that it's not worth adding a samples page until we can at least get our experiments pages to appear on Google. I did some research, and people have had success getting their React Router apps indexed by Google, and it looks like this tool might help get ours indexed: https://search.google.com/search-console/about?hl=en&utm_source=wmx&utm_medium=wmx-welcome

**Comment by arielsvn** [comment]
Oh yes, we use that, and appear on the first page for some [experiment accession codes](https://www.google.com/search?q=gse36133). 

![image](https://user-images.githubusercontent.com/1882507/61542339-5a6f8480-aa0f-11e9-910d-48f3783e9911.png)

What I like about the sample accession codes is that there isn't much competition for those terms. So we would be able to rank higher.

**Comment by arielsvn** [comment]
We added a first version of the samples page and started getting traffic through it. 

#874 will add them to the sitemap.
