### ISSUE TITLE
Terms of Services & Privacy Page

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#71]
Get copy from http://cognoma.org/#!/terms & http://cognoma.org/#!/privacy

**Comment by dvenprasad** [comment]
We would also need to add a license page. Copy for refine.bio license is here: [https://github.com/AlexsLemonade/refinebio/blob/dev/LICENSE](https://github.com/AlexsLemonade/refinebio/blob/dev/LICENSE)
