### ISSUE TITLE
Sitemap.xml is not being generated

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-frontend#731]
After changing the API urls to include a version the sitemap.xml is no longer being generated on deploys.

Next step would be to add v1 to the ```cacheBackend.js``` script or possibly add ```latest``` to the api so endpoints like these will always just go to the latest version.

**Comment by davidsmejia** [comment]
As it currently is being generated. For the 50k experiments, it makes 100 api requests for ~500 experiments per request. It also looks like almost all of them are erring out. I think the best move would be to create a separate api endpoint that could just return the accession_code, title, and maybe urls in ```created_at``` order ascending so we could possibly just get from the last one and insert into the sitemap by default instead of asking for all 50k + going forward. 

This would also allow for us to add autocomplete / suggestions into search.

**Comment by davidsmejia** [comment]
This might also be a more performant option for the future. Just putting it here for future reference.
 
https://github.com/taskrabbit/elasticsearch-dump

**Comment by arielsvn** [comment]
But with another API endpoint wouldn't we be in the same situation? Why are the requests failing?

The number of accessions could be way bigger if we also included the samples in the sitemap.

**Comment by davidsmejia** [comment]
@arielsvn I think the problem is that Django can't handle the 1,000 requests in such a short amount of time. So my thinking now is that it would be best to query ES directly as save the results to s3. I'm not sure where that command should be executed from but it would have to have access to the ES endpoint.
