### ISSUE TITLE
Compendium Page -> Normalized compendium / quantpendium

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-frontend#758]
Based on https://github.com/AlexsLemonade/refinebio/issues/1587 it's clear that this is desired. We should update the compendium page to continue to provide the headline normalized compendium, but also to provide - either below the fold or after changing selection, a collection of all of the `quant.sf` files that we've generated organized by species.

**Comment by dvenprasad** [comment]
Species Compendia and Quant.sf Compendia will be tucked under the Compendium Page. 

Copy to contextualize the compendium:
`refine.bio Compendium packages the data processed by refine.bio pipelines for flexible and broad use by computational biologists and data scientists`

Things that need to go on the Quant.sf Compendia page/section
- Copy: What is it? How was it processed?
- Download mechanism
- Customize the download via API
- Explicitly mention that files they receive are NOT normalized or aggregated.  

Also, do we have information/links to close the loop when users download quant compendia like we do for species compendia? or can we skip it for now? @cgreene @jaclyn-taroni 
![Screen Shot 2019-09-16 at 4 37 00 PM](https://user-images.githubusercontent.com/15315514/64991639-3a89ff00-d8a0-11e9-91b9-a0ab735a2621.png)



## Low Fi:
![quant-compendia-lowfi-annotated](https://user-images.githubusercontent.com/15315514/64991358-ba639980-d89f-11e9-85a2-4e9266c3d5a9.jpg)

**Comment by dvenprasad** [comment]
Mockups:
![compendium-species-compendia-no-examples](https://user-images.githubusercontent.com/15315514/65347527-36febc80-dbad-11e9-8026-b8cbc737196b.png)

![compendium-rna-seq-compendia](https://user-images.githubusercontent.com/15315514/65347528-36febc80-dbad-11e9-8a79-1c10982e71c1.png)



Note: The copy under `Uniformly Processed` needs to be replaced with appropriate copy once the docs are ready. 

Invision Links:
https://invis.io/9SNAJ70ME4D#/384794314_compendium-Species-Compendia-No-Examples

https://invis.io/9SNAJ70ME4D#/384608890_compendium-Rna-Seq-Compendia

Assets:
pipeline illustration
https://invis.io/a/E58AFMU0R6FZ

RNA-seq sample compendia icon
https://invis.io/a/VE8AF3FY3982

I've left comments on the mockup with links for the hyperlinks and about transition.
@davidsmejia let me know if you need anything else from me.

**Comment by jaclyn-taroni** [comment]
@dvenprasad @kurtwheeler per the conversation that happened yesterday -- the issue says `normalized compendium` for what used to be called simply `<species name> compendium` which seems like a good change to me.

**Comment by dvenprasad** [comment]
Sweet. Will update the mockups

**Comment by dvenprasad** [comment]
I've updated my above [comment](https://github.com/AlexsLemonade/refinebio-frontend/issues/758#issuecomment-533667349) with the new mockups and assets. 

In addition to those, downloading page for the normalized compendia needs to change and the little card about the compendia on the landing page also needs to be modified. 

Mockups:
![species-compendia-downloading](https://user-images.githubusercontent.com/15315514/65646987-0c589d80-dfcb-11e9-8cee-0f0d53b329a2.png)


![Screen Shot 2019-09-25 at 7 30 31 PM](https://user-images.githubusercontent.com/15315514/65646995-111d5180-dfcb-11e9-805a-5884d48335b9.png)

Invision:
https://invis.io/9SNAJ70ME4D#/358706636_species-Compendia-Downloading

https://invis.io/9SNAJ70ME4D#/300190943_landing-Page

**Comment by jaclyn-taroni** [comment]
That needs to be stylized as _Danio rerio_ rather than danio rerio.

**Comment by jaclyn-taroni** [comment]
How about:
> refine.bio compendia are collections of samples that have been processed and packaged for broad and flexible use.
for the copy circled above

**Comment by dvenprasad** [comment]
Updated my [comment](https://github.com/AlexsLemonade/refinebio-frontend/issues/758#issuecomment-535267665) addressing @jaclyn-taroni's comments

Also, @arielsvn mentioned @davidsmejia had an idea about adding the file sizes to compendia page, that's a solid idea. I've incorporated those as well.

**Comment by cgreene** [comment]
Completed with #773 / deployed with #795
