### ISSUE TITLE
Update available sample numbers

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-frontend#759]
![Screen Shot 2019-09-16 at 10 35 01 AM](https://user-images.githubusercontent.com/542643/64966936-b6b71f00-d86d-11e9-846c-29648d28ba87.png)

We should make these numbers live! And also take into account the changes from https://github.com/AlexsLemonade/refinebio/issues/1601

**Comment by arielsvn** [comment]
Related to https://github.com/alexslemonade/refinebio-frontend/issues/320 where we also need to update the number of supported organisms.
