### ISSUE TITLE
Add citation info in the footer

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#760]
Related to https://github.com/AlexsLemonade/refinebio/issues/703

We need to add  refine.bio citation info in the footer

`Casey S. Greene, Dongbo Hu, Richard W. W. Jones, Stephanie Liu, David S. Mejia, Rob Patro, Stephen R. Piccolo, Ariel Rodriguez Romero, Hirak Sarkar, Candace L. Savonen, Jaclyn N. Taroni, William E. Vauclain, Deepashree Venkatesh Prasad, Kurt G. Wheeler. **refine.bio: a resource of uniformly processed publicly available gene expression datasets.** URL: https://www.refine.bio `
Also: `_Note that the contributor list is in alphabetical order as we prepare a manuscript for submission_.`

**Comment by arielsvn** [comment]
@dvenprasad can we update one of the designs with this?

**Comment by dvenprasad** [comment]
![Screen Shot 2019-09-23 at 3 41 48 PM](https://user-images.githubusercontent.com/15315514/65457041-af1cea80-de18-11e9-8a4c-362fc28af9cb.png)


Invision: 
https://invis.io/9SNAJ70ME4D#/300190943_landing-Page

@arielsvn let me know if you need anything else
