### ISSUE TITLE
Add a "fork dataset" option on computed datasets

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-frontend#778]
If I download a dataset and realize I forgot a sample, or set the wrong normalization option, I cannot just go back, add a sample or change an option and re-download my sample. It seems like that would be a nice feature to have.

I'm thinking that functionality similar to "forking" would be nice for a dataset. This could probably be done entirely in the frontend. The frontend could just take the data from the previous dataset, create a new one that has it, and then let the user continue to modify it.

**Comment by arielsvn** [comment]
We could also add a button to add all samples to your current dataset.

**Comment by dvenprasad** [comment]
On the dataset delivery page, we want users to be able to:
- Change smashing options and regenerate dataset (or get a new dataset)
- Modify dataset
    - Add all of the samples to current dataset (appends all of the samples to `My Dataset`)
    - Clear out current dataset and add all the samples

Are these are all things we want to support? @kurtwheeler @arielsvn @jaclyn-taroni 
If yes, I'll start creating some low-fi mockups.

**Comment by kurtwheeler** [comment]
That sounds good to me!

**Comment by jaclyn-taroni** [comment]
To clarify

> Clear out current dataset and add all the samples

Means if I have samples in `My Dataset`, get rid of those and repopulate `My Dataset` with the samples that were included in the previous dataset that I'm on the page for?

Everything else sounds good to me, just want to clarify the last point.

**Comment by dvenprasad** [comment]
Yes, that is correct.

**Comment by dvenprasad** [comment]
The option to modify will only be available on the following dataset states:
- Processed
- Expired

Users cannot fork dataset when it is being processed or if there's an error processing. 

#800 will explore if `undo` can be implemented without having to add too much complexity to current system. 

**Hi-fi Mockups:**
I've highlighted the additions on the mockups in pink.

![download-dataset-download-ready](https://user-images.githubusercontent.com/15315514/70079942-b0665280-15d3-11ea-9804-6480cfa5f672.jpg)

![download-dataset-download-ready-change-options](https://user-images.githubusercontent.com/15315514/70080052-df7cc400-15d3-11ea-809a-266acd4cecb3.jpg)


![download-dataset-download-ready-move-dataset](https://user-images.githubusercontent.com/15315514/70080076-e7d4ff00-15d3-11ea-8bbb-f4fed7b0d6e7.png)


![download-dataset-speices-agg-species-view-dataset-appended](https://user-images.githubusercontent.com/15315514/70080083-eb688600-15d3-11ea-8946-bfcf3a478248.jpg)

![download-dataset-speices-agg-species-view-dataset-moved](https://user-images.githubusercontent.com/15315514/70080088-edcae000-15d3-11ea-96c5-cd9cbe82ea6a.jpg)


**Invision:**
https://invis.io/9SNAJ70ME4D#/302048787_download-Dataset-Download-Ready
https://invis.io/9SNAJ70ME4D#/394812745_download-Dataset-Download-Ready-Change-Options
https://invis.io/9SNAJ70ME4D#/394812744_download-Dataset-Download-Ready-Move-Dataset
https://invis.io/9SNAJ70ME4D#/394812746_download-Dataset-Speices-Agg-Species-View-Dataset-Appended
https://invis.io/9SNAJ70ME4D#/394812747_download-Dataset-Speices-Agg-Species-View-Dataset-Moved


@davidsmejia @arielsvn I've left some comments on the screen on Invision that maybe helpful.  Let me know if there's anything you need from me.

**Comment by arielsvn** [comment]
Closed by #815
