### ISSUE TITLE
Change Species Compendia on landing page -> refine.bio compendia

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#808]
Might have slipped through the cracks from #758. It was a lot.

![Screen Shot 2019-12-06 at 10 48 26 AM](https://user-images.githubusercontent.com/15315514/70335979-602b0280-1816-11ea-90a3-f783771b6d4d.png)

 This needs to change to: 

![image](https://user-images.githubusercontent.com/15315514/70336111-936d9180-1816-11ea-986a-3f3c92f1979b.png)

`Learn More` links to the compendia page

Invision:
https://invis.io/9SNAJ70ME4D#/300190943_landing-Page

@davidsmejia let me know if you need anything else

**Comment by davidsmejia** [comment]
closed with #814
