### ISSUE TITLE
Provide a one-button mechanism for users to download all samples from a single experiment

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-frontend#810]
Wherever we display an experiment, we could provide a button for convenience that would create a dataset and allow users to easily download all samples from a single experiment along with associated metadata.

**Comment by arielsvn** [comment]
Right now it's fairly easy for users to get a dataset with a single experiment, with 4 clicks. An additional button would probably reduce it to 2 clicks. Maybe this is an indication that we should do a better job of explaining things?

![2019-12-16 10 01 56](https://user-images.githubusercontent.com/1882507/70917575-95400d80-1feb-11ea-853c-1a1f5a055ab2.gif)

**Comment by dvenprasad** [comment]
We need to think about whether we provide transformation options and advance download options(QN vs non-QN) if they are downloading a single experiment.

**Comment by arielsvn** [comment]
Looks like people are downloading datasets with a single experiment mostly. Out of the 95 datasets that we have processed this year, 79 had a single experiment in them. They were all Scaled by `None` and the only option that changed was whether or not they were quantile normalized (50 yes vs 29 no)

I think we should provide transformation and advance download options.

<details><summary>Code for reference</summary>

```py
>>> datasets = Dataset.objects.all().filter(created_at__gt='2020-01-01', is_processed=True)        
>>> print(datasets.count())
95
>>> count = 0
>>> ids = []
>>> for dataset in datasets:
...     if len(dataset.data.keys()) == 1:
...         count += 1
...         ids.append(dataset.id)
... 
>>> print(count)
79
>>> 
>>> Dataset.objects.filter(id__in=ids).values_list('aggregate_by', 'scale_by', 'quantile_normalize', 'quant_sf_only', 'svd_algorithm').distinct()
<QuerySet [('EXPERIMENT', 'NONE', False, False, 'NONE'), ('EXPERIMENT', 'NONE', True, False, 'NONE')]>
>>> Dataset.objects.filter(id__in=ids, quantile_normalize=True).count()
50
>>> Dataset.objects.filter(id__in=ids, quantile_normalize=False).count()
29
```

</details>

**Comment by dvenprasad** [comment]
Here are the mockups:

![experiment-page-dl-now](https://user-images.githubusercontent.com/15315514/74863464-f05bec80-531b-11ea-9332-8ce6e3bafa18.png)

![experiment-page-dl-now-dl-options](https://user-images.githubusercontent.com/15315514/74863460-f05bec80-531b-11ea-8c1b-cbccae6ac756.png)

![experiment-page-dl-now-dl-options-processing](https://user-images.githubusercontent.com/15315514/74863459-efc35600-531b-11ea-8925-55ce87427d33.png)

![experiment-page-dl-now-processing](https://user-images.githubusercontent.com/15315514/74863463-f05bec80-531b-11ea-8e23-3f242108d65f.png)


On results page:

![search-result-default](https://user-images.githubusercontent.com/15315514/74863466-f0f48300-531b-11ea-9c81-70060d35a495.png)

The variations of the results card is here: https://invis.io/9SNAJ70ME4D#/282838929_search_Results

Annotated mockups:
![rbio-dl-experiment-options](https://user-images.githubusercontent.com/15315514/74864317-657bf180-531d-11ea-83e0-72807502023c.png)

![rbio-dl-experiment-processing](https://user-images.githubusercontent.com/15315514/74864329-6a40a580-531d-11ea-8bce-ff2694f7ee63.png)

![rbio-dl-experiment-indicate](https://user-images.githubusercontent.com/15315514/74864347-6d3b9600-531d-11ea-81fb-043c769698ce.png)


Invision:  https://invis.io/9SNAJ70ME4D#/405695192_experiment-Page-Dl-Now

@arielsvn @davidsmejia let me know if you need anything else
