### ISSUE TITLE
Filter frontend results by `is_processed` and `is_public`

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#84]
https://github.com/AlexsLemonade/refinebio/issues/295

is_public: False, is_processed: False: Never show this result
is_public: True, is_processed: True: Return our results
is_public: True, is_processed: False: Link to source_archive_url

**Comment by Miserlou** [comment]
You should now never get any `is_public: False` results at all, and `is_processed` will be set appropriately after it has been processed. If `is_processed` is never set, you can link out to `source_archive_url`.

**Comment by ramenhog** [comment]
Yup, just linking to the refinebio ticket that will close this https://github.com/AlexsLemonade/refinebio/pull/318
