### ISSUE TITLE
Decide how we are going to deploy the SSR changes

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#857]
https://github.com/AlexsLemonade/refinebio-frontend/pull/853 will be merged soon. We should decide how to deploy it. We have had several discussions about this and there're 3 options.

1. Use [Zeit](https://zeit.co/pricing) they have a free tier however I'm not sure if the 20GB bandwidth limit would be enough for refinebio. I asked and they couldn't provide free support for the project without adding their logo to refinebio's landing page.

2. Use [Serverless](https://serverless.com/blog/serverless-nextjs/) which would deploy to Lambda@Edge. We had some concerns about giving an open-source project control over our AWS account.

3. Write the whole thing configuration from scratch in Terraform.

I lean towards the first option, even if we had to pay their Pro plan. Mainly because it would be the easiest and it integrates automatically with Github. In either case, we'll use their pull request previews.

@davidsmejia @kurtwheeler @cgreene what do you think about this?

**Comment by cgreene** [comment]
$20/mo to make problems ago away in the event that they even arise sounds good to me.
