### ISSUE TITLE
Finish releasing server side rendering

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#862]
We discussed the roadmap for the deployment initially in https://github.com/AlexsLemonade/refinebio-frontend/pull/853#issuecomment-594640628. From those I finished today:

- [x] Merge https://github.com/AlexsLemonade/refinebio-frontend/pull/853
- [x] Create a CCDL team in Zeit, and setup both staging and prod deploys under .now.sh domains
- [x] Setup CCDL team on Zeit connected to refinebio's https://zeit.co/ccdl/refinebio-frontend

We have yet to take care of the following:

- [x] Merge https://github.com/AlexsLemonade/refinebio-frontend/pull/859 which should deploy to production
- [x] Ensure the staging/production configuration is correct for the project in Zeit. I added files to set it up with https://github.com/AlexsLemonade/refinebio-frontend/pull/861 but we still need to merge everything into master to see that it works. [Some docs](https://docs-31e8787wy.zeit.sh/docs/v2/domains-and-aliases/aliasing-a-deployment/#git-staging-aliases)
- [x] Ensure that we can have a domain pointing to the `master` branch. I setup two domains now:
![image](https://user-images.githubusercontent.com/1882507/75927446-655e1480-5e3a-11ea-92cf-5e0bf7a6139d.png)
- [x] Update refine.bio DNS configuration to point to ZEIT servers
  - [x] Staging
  - [x] Production
- [ ] Remove all terraform configuration related to the frontend from the backend project.

**Comment by arielsvn** [comment]
I'm having an issue with Zeit that's very frustrating, where it's not letting me deploy a domain with the `master` branch. When I add it they deploy `dev` instead, which is the default branch of this project.

I filed a ticket with ZEIT to see if there's a way to fix this that doesn't involve changing the default branch of this repository. [Recording of the problem](https://user-images.githubusercontent.com/1882507/76360182-e4e45b80-62f2-11ea-9726-09cc39ca8110.gif)

If this doesn't get fixed soon, we could use ZEIT CLI interface with CI to have both prod and dev deployed. Similar to [this config](https://spectrum.chat/zeit/now/multiple-environments-via-github-deployments~34124374-4365-4abd-a53f-0698315adeb5?m=MTU0ODM3Njc3NTM2NQ==)

**Comment by arielsvn** [comment]
Talked with ZEIT today, they sort of fixed the issue, but it's still having trouble. I think they don't handle well repositories where the default branch isn't `master`.

I added configuration to deploy with CircleCI, but this also failed, still not possible to deploy `master` to one of their domains with this repo. Also, forked this repository and tested with one where `master` was the default branch and it all worked as expected.

I'm very frustrated with ZEIT and need some advice to move forward @davidsmejia @kurtwheeler @cgreene

There're two compromises we would have to make if we wanted to use ZEIT:

1. Change the default branch of the repo to `master`, at least until they fix the issue

2. If we want to use the out-of-the-box GitHub integrations we won't be able to use the staging API in the staging version, because they don't support different [environment variables for staging/prod](https://spectrum.chat/zeit/general/different-secrets-for-production-and-staging-environments~51846996-a72f-4f9e-8b21-7e07df89555b?m=MTU4Mzg5NDM0NDgxNA==)

Their main appeal was how easy it was to set up, but it looks like we hit multiple "corner cases" for them, like a repo where `master` isn't the default branch and a staging deploy using staging API. Potentially we could also explore other solution from #857

**Comment by cgreene** [comment]
Switch primary branch to master looks pretty straightforward. I guess the downside is that browsing github will show what's running instead of what's ready to be deployed.

Point 2 seems pretty annoying too. How hard is to modify theirs for the staging deployment?

**Comment by arielsvn** [comment]
Finally got staging/production deploys working, I had to change the default branch to `master` and trigger these deploys via CircleCI. See [refinebio.now.sh](https://refinebio.now.sh) and [refinebio-staging.now.sh](https://refinebio-staging.now.sh).

I'm going to update now the DNS configuration for staging.refine.bio to ensure it points to the ZEIT servers. And if that works well, update www.refine.bio.

**Comment by arielsvn** [comment]
Closing this, refinebio's is now server-rendered. I checked the page speed insights and this reduced the time to first meaningful paint by more than 30%, for the search/experiment pages.

I'll file another issue in the backend to remove the terraform config related to the FE.
