### ISSUE TITLE
Link to different examples based on the technology in user's dataset

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#906]
refine.bio examples is being restructured! 🎉  It is going to be organized by technology(https://github.com/AlexsLemonade/refinebio-examples/issues/102) 

We will need to change how we link to specific examples on the dataset download page 

![Screen Shot 2020-07-07 at 11 23 54 AM](https://user-images.githubusercontent.com/15315514/86805994-6dc39780-c046-11ea-9722-eab9c8484acd.png)

We should show different links to users based on the technology of the data they downloaded. 
Will provide more specific links once the restructure is done.

**Comment by cansavvy** [comment]
This should be easier to do after the restructuring in https://github.com/AlexsLemonade/refinebio-examples/pull/120 is done.

**Comment by dvenprasad** [comment]
We should keep `Learn more about how we source and process our data` as is but change the other links based on the technology in user's dataset

RNA-seq links
- [Convert ENSEMBL IDs to Gene Symbols](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/gene-id-annotation_rnaseq_01_ensembl.html)
- [Follow an example differential expression analysis](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential-expression_rnaseq_01.html)
- [Follow a example pathway analysis ](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/pathway-analysis_rnaseq_02_gsea.html)
- See what other analyses you can do with refine.bio data -> link to homepage

Microarray links
- [Convert ENSEMBL IDs to Gene Symbols](https://alexslemonade.github.io/refinebio-examples/02-microarray/gene-id-annotation_microarray_01_ensembl.html)
- [Follow an example differential expression analysis](https://alexslemonade.github.io/refinebio-examples/02-microarray/differential-expression_microarray_01_2-groups.html)
- [Follow a example pathway analysis ](https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_02_gsea.html)
- See what other analyses you can do with refine.bio data -> link to homepage

Mixed Technology links
- [Convert ENSEMBL IDs to Gene Symbols for microarray data](https://alexslemonade.github.io/refinebio-examples/02-microarray/gene-id-annotation_microarray_01_ensembl.html)
- [Convert ENSEMBL IDs to Gene Symbols for RNA-seq data](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/gene-id-annotation_rnaseq_01_ensembl.html)
- [Follow an example differential expression analysis for microarray data](https://alexslemonade.github.io/refinebio-examples/02-microarray/differential-expression_microarray_01_2-groups.html)
- [Follow an example differential expression analysis for RNA-seq data](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential-expression_rnaseq_01.html)
- See what other analyses you can do with refine.bio data -> link to homepage
