### ISSUE TITLE
Make Alternate Accession IDs searchable

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-frontend#919]
### Summary
It appears a dataset might have an alternate accession id on its dataset page but it isn't searchable: 

<img width="334" alt="Screen Shot 2020-08-12 at 12 34 57 PM" src="https://user-images.githubusercontent.com/23458084/90042357-9586ca80-dc98-11ea-9ebd-80000213469b.png">

But that this wouldn't show up on the search: 

<img width="646" alt="Screen Shot 2020-08-12 at 12 37 51 PM" src="https://user-images.githubusercontent.com/23458084/90042425-a8999a80-dc98-11ea-959d-ea0f2e27066c.png">

A user might search for this dataset using a GEO id and then think we don't have it even though we do and you can find it using the SRA ID. In this example: `SRP149884` comes up but `GSE115397` says "no results". 

This is the example dataset I'm referring to: 
https://www.refine.bio/experiments/SRP149884/non-inflammatory-tumor-microenvironment-of-diffuse-intrinsic-pontine-glioma-dipg

I have no idea if this has been discussed previously or how difficult it is to implement but I think it would help users out a lot (and prevent people from leaving the site because they think we don't have a dataset we actually do have)>

**Comment by cansavvy** [comment]
This is a part of the protocol but it was temporarily not working. According to @wvauclain it was temporarily not working: 

> the reason why it didn't show up is probably because I am running the management command right now to populate that field

**Comment by wvauclain** [comment]
This'll be fixed as soon as the management command finishes running that is populating this field on the backend.
