### ISSUE TITLE
Restructure examples we present on homepage 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#926]
refine.bio examples are revamped. Once it goes live, the current examples we display on the home page are not accurate anymore.

We should change how we present these to reflect the updated refinebio examples content. 

![Screen Shot 2020-10-07 at 11 12 02 AM](https://user-images.githubusercontent.com/15315514/95350871-a1ed6500-088e-11eb-9775-39ebf1afa17e.png)

Tagging @cansavvy to help figure out which examples we should link

**Comment by jaclyn-taroni** [comment]
Tagging @cansavvy again

**Comment by cansavvy** [comment]
I wonder whether we should instead move to linking to the intro to microarray and intro to rna-seq pages and/or the getting started page? Now that we have split things by technology I am not sure whether to link people to rna-seq differential expression or microarray differential expression. 

OR should we post both technologies examples? 

If we do go the specific example route, I would say differential expression (two groups version) for sure and probably clustering and maybe one of the pathway analyses GSEA?

**Comment by dvenprasad** [comment]
We can definitely link to both technologies. I think a combination of specific examples (i.e an analysis) and something generic like getting started and intro would be good. 

Another thing, we want to provide links to things which would cover both our user types: Bio Expert and Data Whiz (ooo boy been a long time since I brought these up). I'm inclined to leave the use your data alongside refine.bio (for the Data Whiz) unless there is a more apt example/thing we can direct them to.

**Comment by jaclyn-taroni** [comment]
> We can definitely link to both technologies. I think a combination of specific examples (i.e an analysis) and something generic like getting started and intro would be good.

If we use this existing structure, we now have several examples we can link to which I'll detail below.

#### Differential expression

- [Differential expression analysis: microarray - 2 groups](https://alexslemonade.github.io/refinebio-examples/02-microarray/differential-expression_microarray_01_2-groups.html)
- [Differential expression analysis: microarray - several groups](https://alexslemonade.github.io/refinebio-examples/02-microarray/differential-expression_microarray_02_several-groups.html)
- [Differential expression analysis: RNA-seq](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential-expression_rnaseq_01.html) (we only have a 2 group example at the moment).

#### Pathway analysis

- [Pathway analysis: Microarray - Overrepresentation Analysis](https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_01_ora.html)
- [Pathway analysis: Microarray - Gene Set Enrichment Analysis](https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_02_gsea.html)
- [Pathway analysis: Microarray - Gene Set Variation Analysis](https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_03_gsva.html)
- [Pathway analysis: RNA-seq - Overrepresentation Analysis](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/pathway-analysis_rnaseq_01_ora.html)
- [Pathway analysis: RNA-seq - Gene Set Enrichment Analysis](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/pathway-analysis_rnaseq_02_gsea.html)
- [Pathway analysis: RNA-seq - Gene Set Variation Analysis](https://alexslemonade.github.io/refinebio-examples/03-rnaseq/pathway-analysis_rnaseq_03_gsva.html)

@dvenprasad if you have some criteria we should use (e.g., perceived popularity based on experience), we can help you narrow down which specific examples to display. 

Agree with @cansavvy that a clustering/heatmap example would probably be nice! I think it's a matter of how many specific examples we want and how broad we want to go on the home page.

I also understand that one of the recommendations from the user evals was a need for a home page (not sure if that should be tracked in this repository or over on [`refinebio-examples`](https://github.com/AlexsLemonade/refinebio-examples)). I think that's where we should link "generically" - i.e., if you want to get started with any of our examples.

**Comment by jaclyn-taroni** [comment]
Side note: Advanced topics is generally where I'd point a Data Whiz. That's currently under construction: https://alexslemonade.github.io/refinebio-examples/04-advanced-topics/00-intro-to-advanced-topics.html

**Comment by dvenprasad** [comment]
![Screen Shot 2021-03-04 at 2 23 07 PM](https://user-images.githubusercontent.com/15315514/110018384-39979800-7cf5-11eb-8020-d3af8220b26e.png)

CTA Links: 
- Get Started -> refine.bio examples homepage
- Differential Expression - RNA-seq - https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential-expression_rnaseq_01.html
- Differential Expression - microarray - https://alexslemonade.github.io/refinebio-examples/02-microarray/differential-expression_microarray_01_2-groups.html
- Pathway analysis- RNA-seq - https://alexslemonade.github.io/refinebio-examples/03-rnaseq/pathway-analysis_rnaseq_02_gsea.html
- Pathway analysis- microarray - https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_02_gsea.html

Get started card icon : https://invis.io/a/cklv99zom00es0pq3zsy87ov6

Invision link: https://invis.io/9SNAJ70ME4D#/300190943_landing-Page
