### ISSUE TITLE
Search page using accession codes isn't working

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-frontend#927]
## The problem:

I've tried this with a few accession codes that I know exist and the search page can't find them

For example: 

This search for RNA-seq experiment SRP133573 comes up blank

https://www.refine.bio/search?q=SRP133573

<img width="668" alt="Screen Shot 2020-11-11 at 9 29 35 AM" src="https://user-images.githubusercontent.com/23458084/98823715-6ea77400-2400-11eb-8195-076d830c11b4.png">

But this experiment is here: https://www.refine.bio/experiments/SRP133573/identification-of-transcription-factor-relationships-associated-with-androgen-deprivation-therapy-response-and-metastatic-progression-in-prostate-cancer

Not sure if it matters, but I've been on Chrome.

**Comment by cansavvy** [comment]
This is not RNA-seq specific, because I've tried `GSE24862` and that also doesn't work.

**Comment by kurtwheeler** [comment]
Both of these experiments now come up, at least for now. I've made a new issue to track the fact that I had to run a thing manually that was supposed to be run automatically.
