### ISSUE TITLE
Allow unprocessed datasets to be owned by anyone

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-frontend#946]
https://github.com/AlexsLemonade/AdminItems/issues/338

As far as I can tell, the API should currently support users setting `start=True` for datasets that were created by someone else. This means that MetaSRA can create datasets, then give them to the users unprocessed, allowing the user to trigger the smasher job and download the dataset themself.

This prevents us from smashing a bunch of datasets that no one actually wants.

I think this is only a frontend change? @davidsmejia can you weigh in with details on what needs to be changed to support this?

**Comment by davidsmejia** [comment]
I think the proposed change will be to add a Download Now button next to add to dataset where you can trigger a popup that provides prefilled download options (matching the existing dataset) and allows for email and terms fill in.
