### ISSUE TITLE
Add reponsiveness

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#95]
(Edit by Deepa)
### Context
Responsiveness was not handled as part of keytar kurt and needs to be added as part of marimba miso.

### Problem or idea
refine.bio is not responsive and would be almost impossible to use on smaller devices. 

### Solution or next step
 Evaluate items that need responsiveness beyond just stacking with @ramenhog and find a solution.

**Comment by ramenhog** [comment]
Currently these pages are responsive on mobile in the `ramenhog/feature/responsiveness` branch:

* Main page
* Results page (except for filters)
* Header menu
* Footer
* Experiment page
* Downloads review page

**Comment by Miserlou** [comment]
This is very close, I think the final download button is the only one not working:

![screen shot 2018-07-26 at 3 19 47 pm](https://user-images.githubusercontent.com/139987/43283612-5fafdfc2-90e7-11e8-8519-bab58b610613.png)

**Comment by Willv19** [comment]
It looks like the 404 page also needs to be made responsive:
![2018-07-30-10 22 15-screenshot](https://user-images.githubusercontent.com/13942258/43403205-7b3fd2bc-93e2-11e8-93d8-512f6d72de2f.png)

**Comment by jaclyn-taroni** [comment]
@arielsvn and @dvenprasad - should this be broken down into several page-specific tickets for the public beta milestone?

**Comment by arielsvn** [comment]
Yes I think that's a good idea. I'll meet with @dvenprasad to talk about which ones should be addressed first. Closing this.
